Salesforce CPQ/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Number of quote for which the approval request is generated.</description>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Approver associated with this Approval.</description>
    <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
    <label>Approver</label>
    <referenceTo>sbaa__Approver__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Status__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Status__c</fullName>
    <description>Status of this approval.</description>
    <inlineHelpText>Status of this approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sbaa__Approver__c/sbaa__Approver__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approver__c/fields/sbaa__User__c.field-meta.xml
<CustomField>
    <fullName>sbaa__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If Approver is a single User, lookup to that User</description>
    <inlineHelpText>If Approver is a single User, lookup to that User</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetApproversEmail_Test.cls
/**
* @author       APB
* @description  GetApproversEmail_Test
*/
@isTest
public class GetApproversEmail_Test {

    /**
    * @author       APB
    * @description  Method used to create the records
    */
    @testSetup
    public static void createRecords(){

    Group groupTest=new Group();
    groupTest.Name= 'test group';
    insert groupTest;
    User productManagerUser = (User)TestFactory.createSObject(new User(), 'TestFactoryDefaults.ProductManagerUserDefaults', true);
    sbaa__Approver__c userApprover= new sbaa__Approver__c();
    userApprover.sbaa__User__c = productManagerUser.Id;
    userApprover.Name= 'product manager user';
    insert userApprover;    
    
    sbaa__Approver__c groupApprover= new sbaa__Approver__c();
    groupApprover.sbaa__GroupId__c = groupTest.Id;
    groupApprover.Name= 'group Approver';
    insert groupApprover;
        
    sbaa__Approval__c userApproval= new sbaa__Approval__c();
    userApproval.sbaa__RecordField__c='Quote__c';
    userApproval.sbaa__Status__c= 'Requested';
    userApproval.sbaa__ApprovalStep__c= 1;
    userApproval.sbaa__Approver__c= userApprover.Id;
    insert userApproval;
    
    sbaa__Approval__c groupApproval= new sbaa__Approval__c();
   	groupApproval.sbaa__RecordField__c='Quote__c';
   	groupApproval.sbaa__Status__c= 'Requested';
    groupApproval.sbaa__ApprovalStep__c= 2;
    groupApproval.sbaa__Approver__c= groupApprover.Id;
    insert groupApproval;
   
    }

    @IsTest
    public static void sendRecallEmailToAnUser(){
        List<Id> listApprovals= new List<Id>(); 
        
       	sbaa__Approval__c userApproval = [Select Id from sbaa__Approval__c where sbaa__ApprovalStep__c= 1];
        listApprovals.add(userApproval.Id);
       
        
        GetApproversEmail.InputVariables inputVariables = new GetApproversEmail.InputVariables();
        inputVariables.approvalIds= listApprovals;
        List<GetApproversEmail.InputVariables> listInputVariables = new List<GetApproversEmail.InputVariables>();
        
        listInputVariables.add(inputVariables);
        
        User productManagerUser = [SELECT Id from User LIMIT 1];
  
        Test.startTest();
         List<GetApproversEmail.OutputParameters> listApprovers = GetApproversEmail.getApproverIds(listInputVariables);
        System.assertEquals(1, listApprovers[0].approverIds.size(),'The email should be sent to the user');
        
   		Test.stopTest();
    }
    
    @IsTest
    public static void sendRecallEmailToAGroup(){
        List<Id> listApprovals= new List<Id>();
            
        Group groupTest= [Select id from Group where Name ='test group'];
    	User productManagerUser = [SELECT Id from User LIMIT 1];
    	
        Test.startTest();
      
        sbaa__Approval__c groupApproval= [Select Id from sbaa__Approval__c where sbaa__ApprovalStep__c= 2];
        GroupMember grMember = new GroupMember();
    	grMember.UserOrGroupId= productManagerUser.Id;
    	grMember.GroupId= groupTest.Id;
    	insert grMember;
        listApprovals.add(groupApproval.Id);
        
        GetApproversEmail.InputVariables inputVariables = new GetApproversEmail.InputVariables();
        inputVariables.approvalIds= listApprovals;
        List<GetApproversEmail.InputVariables> listInputVariables = new List<GetApproversEmail.InputVariables>();
        
        listInputVariables.add(inputVariables);
     
        List<GetApproversEmail.OutputParameters> listApprovers = GetApproversEmail.getApproverIds(listInputVariables);
        System.assertEquals(1, listApprovers[0].approverIds.size(),'The email should be sent to the approved by user');
        
        Test.stopTest();

    }

}