force-app/main/default/objects/SalesAreaLink__c/SalesAreaLink__c.object-meta.xml
<CustomObject>
    <description>Establishes n:m relation between Sales Area and Account.</description>
    <label>Sales Area Link</label>
    <nameField>
        <displayFormat>SAL-{000000}</displayFormat>
        <label>Sales Area Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesAreaLink__c/fields/ftxt_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>ftxt_DistributionChannel__c</fullName>
    <description>Pull Input from Sale Area Distribution Channel</description>
    <formula>TEXT(mdr_SalesArea__r.pkl_DistributionChannel__c)</formula>
    <label>Distribution Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesAreaLink__c/fields/ftxt_Division__c.field-meta.xml
<CustomField>
    <fullName>ftxt_Division__c</fullName>
    <formula>TEXT( mdr_SalesArea__r.pkl_Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesAreaLink__c/fields/mdr_Account__c.field-meta.xml
<CustomField>
    <fullName>mdr_Account__c</fullName>
    <description>Create connection between Sales Area Link and Account object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Areas</relationshipLabel>
    <relationshipName>SalesAreaLinks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesAreaLink__c/fields/mdr_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>mdr_SalesArea__c</fullName>
    <description>Create connection between Sales Area Link and Sales Area object</description>
    <label>Sales Area</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Sales Area Links</relationshipLabel>
    <relationshipName>SalesAreaLinks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesAreaLinkTriggerHandler.cls
public without sharing class SalesAreaLinkTriggerHandler {
    
    public static void handleBeforeInsert(List<SalesAreaLink__c> newRecords) {
        checkForDuplicates(newRecords);
    }
    
    public static void checkForDuplicates(List<SalesAreaLink__c> newRecords){
        Set<Id> accountIds = new Set<Id>();
        Map<Id,SalesAreaLink__c> accountSDCMap = new Map<Id,SalesAreaLink__c>();
        
        for(SalesAreaLink__c sal : newRecords){
            if(sal.mdr_Account__c != null)
                accountIds.add(sal.mdr_Account__c);
        }
        
        List<SalesAreaLink__c> existingSDCustomers = [Select Id,mdr_Account__c,ftxt_DistributionChannel__c,ftxt_Division__c,mdr_SalesArea__c
                                                      from SalesAreaLink__c where mdr_Account__c IN : accountIds];
        
        for(SalesAreaLink__c existing : existingSDCustomers){
            accountSDCMap.put(existing.mdr_Account__c,existing);
        }
        
        for(SalesAreaLink__c newSDCustomer : newRecords){
            if(accountSDCMap.keySet().contains(newSDCustomer.mdr_Account__c)){
                if(accountSDCMap.get(newSDCustomer.mdr_Account__c).mdr_SalesArea__c == newSDCustomer.mdr_SalesArea__c &&
                   accountSDCMap.get(newSDCustomer.mdr_Account__c).ftxt_DistributionChannel__c == newSDCustomer.ftxt_DistributionChannel__c &&
                   accountSDCMap.get(newSDCustomer.mdr_Account__c).ftxt_Division__c == newSDCustomer.ftxt_Division__c) {
                       newSDCustomer.addError('Sales Data Customer record already exist for combination of: Sales Organization, Distribution Channel and Division');
                   }
            }
        }
    }
}