force-app/main/default/objects/Apttus_AgreementParty__c/Apttus_AgreementParty__c.object-meta.xml
<CustomObject>
    <description>This object will hold information about each party&#39;s role in the agreement especially in multicontractual agreements.</description>
    <label>Agreement Party</label>
    <nameField>
        <label>Agreement Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_AgreementParty__c/fields/lkp_AgreementParty__c.field-meta.xml
<CustomField>
    <fullName>lkp_AgreementParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agreement Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreement Party Name</relationshipLabel>
    <relationshipName>Agreement_Party</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_AgreementParty__c/fields/pkl_MultyPartySignatureType__c.field-meta.xml
<CustomField>
    <fullName>pkl_MultyPartySignatureType__c</fullName>
    <description>Type of signature which the party mantioned - signing the agreement - will use</description>
    <label>Multy Party Signature Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eSignature</fullName>
                <default>true</default>
                <label>eSignature</label>
            </value>
            <value>
                <fullName>Wet Ink Signature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_AgreementParty__c/fields/pkl_PartyRole__c.field-meta.xml
<CustomField>
    <fullName>pkl_PartyRole__c</fullName>
    <description>Agreement Party Role- including in a contract</description>
    <inlineHelpText>Agreement Party Role- including in a contract</inlineHelpText>
    <label>Party Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ETAS Legal Entity</fullName>
                <default>true</default>
                <label>ETAS Legal Entity</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AgreementPartyController.cls
public with sharing class AgreementPartyController {

    public static final String INSERT_PARTY_ERROR = 'Unable to save Agreement Parties. Please check required fields.';
    public static final String EXCEPTION_ERROR = 'An unexpected error occurred while saving Agreement Parties.';    
    
    @AuraEnabled
    public static Boolean createAgreementParties(List<Apttus_AgreementParty__c> parties) {
        Boolean resp = true;        
            for (Apttus_AgreementParty__c party : parties) {            
                if (String.isBlank(party.pkl_PartyRole__c) || String.isBlank((String)party.lkp_AgreementParty__c)) {
                    return false;
                }
            }
			Database.SaveResult[] results = Database.insert(parties, true);			        	
				for (Database.SaveResult res : results) {
					if (!res.isSuccess()) {
						resp = false;        			
                        for (Database.Error err : res.getErrors()) {
                            //Logger.error(INSERT_PARTY_ERROR + err.getMessage());
                        }                                                            
                    }
                    //Logger.saveLog();
                }        
        return resp;
    }

    @AuraEnabled
    public static List<String> getRolePicklistValues() {
        List<String> roles = new List<String>();
        Schema.DescribeFieldResult fieldResult = Apttus_AgreementParty__c.pkl_PartyRole__c.getDescribe();
        for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
            roles.add(entry.getValue());
        }
        return roles;
    }
    
    @AuraEnabled
    public static List<String> getSignatureTypeValues() {
        List<String> types = new List<String>();
        Schema.DescribeFieldResult fieldResult = Apttus_AgreementParty__c.pkl_MultyPartySignatureType__c.getDescribe();
        for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
            types.add(entry.getValue());
        }
        return types;
    }
}