force-app/main/default/objects/APTS_integration_Allowed__c/APTS_integration_Allowed__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Switch for callouts happening</description>
    <label>Integration_Allowed</label>
</CustomObject>

force-app/main/default/objects/APTS_integration_Allowed__c/fields/APTS_Allow_Callout__c.field-meta.xml
<CustomField>
    <fullName>APTS_Allow_Callout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Callout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APTS_AgreementTriggerHandler.cls
/**
* @Name: APTS_AgreementTriggerHandler
* @Author: APTTUS
* @CreateDate: 07/31/2019
* @Description: Triggerhandler for Agreement Trigger.
-----------------------------------------------------------------------------------------------
MODIFY:
07/21/22: Not needed for the Accelerator offering.
**/
public class APTS_AgreementTriggerHandler{
    /*
    public static void onAfterUpdate(List<Apttus__APTS_Agreement__c> newList, Map<Id,Apttus__APTS_Agreement__c> oldMap){
        APTS_integration_Allowed__c integrationallowed = APTS_integration_Allowed__c.getInstance('Integration_Allowed');
        Boolean allowcallouts = integrationallowed.APTS_Allow_Callout__c;
        APTS_AgreementTriggerHelper.activateFullySignedAgreement(newList,oldMap);
        if(allowcallouts){
            APTS_AgreementTriggerHelper.AgreementActive(newList,oldMap);
        }
    }
    public static void onAfterInsert(List<Apttus__APTS_Agreement__c> newList){APTS_AgreementTriggerHelper.AgreementDocFormatInsert(newList);
    }
    
    public static void onBeforeUpdate(List<Apttus__APTS_Agreement__c> newList, Map<Id,Apttus__APTS_Agreement__c> oldMap){
        APTS_AgreementTriggerHelper.AgreementDocFormatUpdate(newList);
    }
    */
}