force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>false</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/lkp_SalesDataCustomer__c.field-meta.xml
<CustomField>
    <fullName>lkp_SalesDataCustomer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Structure sales based on a regional division of the market.</description>
    <label>Sales Data Customer</label>
    <referenceTo>SalesAreaLink__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <description>Structure sales based on a regional division of the market.</description>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{000}</displayFormat>
        <label>Sales Area</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesAreaLink__c/SalesAreaLink__c.object-meta.xml
<CustomObject>
    <description>Establishes n:m relation between Sales Area and Account.</description>
    <label>Sales Area Link</label>
    <nameField>
        <displayFormat>SAL-{000000}</displayFormat>
        <label>Sales Area Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesAreaLink__c/fields/mdr_Account__c.field-meta.xml
<CustomField>
    <fullName>mdr_Account__c</fullName>
    <description>Create connection between Sales Area Link and Account object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Areas</relationshipLabel>
    <relationshipName>SalesAreaLinks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesAreaLink__c/fields/mdr_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>mdr_SalesArea__c</fullName>
    <description>Create connection between Sales Area Link and Sales Area object</description>
    <label>Sales Area</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Sales Area Links</relationshipLabel>
    <relationshipName>SalesAreaLinks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteBeforeDeleteTest.cls
/**
* @author       TLQ1KOR
* @description  QuoteBeforeDeleteTest: Class used to test the flow QuoteBeforeDelete
*/
@isTest
public class QuoteBeforeDeleteTest {
    
    @testSetup
    public static void createRecords(){
        Account testAccount = (Account)TestFactory.createSObject(new Account(), true);
        
        SalesArea__c salesArea = (SalesArea__c)TestFactory.createSObject(new SalesArea__c(), true);
        
         //Create Sales Data Customer
        SalesAreaLink__c salesAreaLink = (SalesAreaLink__c)TestFactory.createSObject(new SalesAreaLink__c(),'TestFactoryDefaults.SalesAreaLinkDefaults', false);
        salesAreaLink.mdr_Account__c = testAccount.Id;
        salesAreaLink.mdr_SalesArea__c = salesArea.Id;
        insert salesAreaLink;
        
        
        Opportunity testOpp = (Opportunity)TestFactory.createSObject(new Opportunity());
        testOpp.AccountId = testAccount.Id;
        testOpp.lkp_SalesDataCustomer__c = salesAreaLink.Id;
        insert testOpp;
    }
    
    @IsTest
    public static void successfulDeleteWhenStatusDraft(){
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        
        SBQQ__Quote__c testQuote = (SBQQ__Quote__c)TestFactory.createSObject(new SBQQ__Quote__c());
        testQuote.SBQQ__Opportunity2__c = testOpp.Id;
        testQuote.SBQQ__Status__c = 'Draft';
        insert testQuote;
        
        Test.startTest();
        Database.DeleteResult result = Database.delete(testQuote, false);
        Test.stopTest();
        
        Assert.isTrue(result.isSuccess(), 'Quote with Draft status should be deletable');
    }
    
    @IsTest
    public static void successfulDeleteWhenStatusApproved(){
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        
        SBQQ__Quote__c testQuote = (SBQQ__Quote__c)TestFactory.createSObject(new SBQQ__Quote__c());
        testQuote.SBQQ__Opportunity2__c = testOpp.Id;
        testQuote.SBQQ__Status__c = 'Approved';
        insert testQuote;
        
        Test.startTest();
        Database.DeleteResult result = Database.delete(testQuote, false);
        Test.stopTest();
        
        Assert.isTrue(result.isSuccess(), 'Quote with Approved status should be deletable');
    }
    
    @IsTest
    public static void successfulDeleteWhenStatusRejected(){
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        
        SBQQ__Quote__c testQuote = (SBQQ__Quote__c)TestFactory.createSObject(new SBQQ__Quote__c());
        testQuote.SBQQ__Opportunity2__c = testOpp.Id;
        testQuote.SBQQ__Status__c = 'Rejected';
        insert testQuote;
        
        Test.startTest();
        Database.DeleteResult result = Database.delete(testQuote, false);
        Test.stopTest();
        
        Assert.isTrue(result.isSuccess(), 'Quote with Rejected status should be deletable');
    }
    
    @IsTest
    public static void failedDeleteWhenStatusApprovalPending(){
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        
        SBQQ__Quote__c testQuote = (SBQQ__Quote__c)TestFactory.createSObject(new SBQQ__Quote__c());
        testQuote.SBQQ__Opportunity2__c = testOpp.Id;
        testQuote.SBQQ__Status__c = 'Approval Pending';
        insert testQuote;
        
        Test.startTest();
        Database.DeleteResult result = Database.delete(testQuote, false);
        Test.stopTest();
        
        //Assert.isFalse(result.isSuccess(), 'Quote with Approval Pending status should not be deletable');
    }
   @IsTest
    public static void successfulDeleteWhenStatusInReview(){
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        
        SBQQ__Quote__c testQuote = (SBQQ__Quote__c)TestFactory.createSObject(new SBQQ__Quote__c());
        testQuote.SBQQ__Opportunity2__c = testOpp.Id;
        testQuote.SBQQ__Status__c = 'In Review';
        insert testQuote;
        
        Test.startTest();
        Database.DeleteResult result = Database.delete(testQuote, false);
        Test.stopTest();
        
        Assert.isTrue(result.isSuccess(), 'Quote with In Review status should be deletable');
    }
    
    @IsTest
    public static void successfulDeleteWhenStatusDenied(){
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        
        SBQQ__Quote__c testQuote = (SBQQ__Quote__c)TestFactory.createSObject(new SBQQ__Quote__c());
        testQuote.SBQQ__Opportunity2__c = testOpp.Id;
        testQuote.SBQQ__Status__c = 'Denied';
        insert testQuote;
        
        Test.startTest();
        Database.DeleteResult result = Database.delete(testQuote, false);
        Test.stopTest();
        
        Assert.isTrue(result.isSuccess(), 'Quote with Denied status should be deletable');
    }
}