force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>false</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/BoschPartner_PartnerFunction__c/BoschPartner_PartnerFunction__c.object-meta.xml
<CustomObject>
    <label>Bosch Partner: Partner Function</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Partner Counter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bosch Partner: Partner Functions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BoschPartner_PartnerFunction__c/fields/lkp_SalesDataCustomer__c.field-meta.xml
<CustomField>
    <fullName>lkp_SalesDataCustomer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Data Customer</label>
    <referenceTo>SalesAreaLink__c</referenceTo>
    <relationshipLabel>Bosch Partner: Partner Functions</relationshipLabel>
    <relationshipName>BoschPartner_PartnerFunctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BoschPartner_PartnerFunction__c/fields/mdr_BoschPartnerFunction__c.field-meta.xml
<CustomField>
    <fullName>mdr_BoschPartnerFunction__c</fullName>
    <label>Bosch Partner Function</label>
    <referenceTo>BoschPartnerFunction__c</referenceTo>
    <relationshipLabel>Bosch Partner: Partner Functions</relationshipLabel>
    <relationshipName>BoschPartnerPartnerFunction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BoschPartner_PartnerFunction__c/fields/ReferencedAccount__c.field-meta.xml
<CustomField>
    <fullName>ReferencedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Referenced Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bosch Partner: Partner Functions</relationshipLabel>
    <relationshipName>BoschPartner_PartnerFunctions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BoschPartnerFunction__c/BoschPartnerFunction__c.object-meta.xml
<CustomObject>
    <label>Bosch Partner Function</label>
    <nameField>
        <label>Partner Function text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bosch Partner Functions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BoschPartnerFunction__c/fields/txt_PartnerFunction__c.field-meta.xml
<CustomField>
    <fullName>txt_PartnerFunction__c</fullName>
    <label>Partner Function</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/lkp_SalesDataCustomer__c.field-meta.xml
<CustomField>
    <fullName>lkp_SalesDataCustomer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Structure sales based on a regional division of the market.</description>
    <label>Sales Data Customer</label>
    <referenceTo>SalesAreaLink__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <description>Structure sales based on a regional division of the market.</description>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{000}</displayFormat>
        <label>Sales Area</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesAreaLink__c/SalesAreaLink__c.object-meta.xml
<CustomObject>
    <description>Establishes n:m relation between Sales Area and Account.</description>
    <label>Sales Area Link</label>
    <nameField>
        <displayFormat>SAL-{000000}</displayFormat>
        <label>Sales Area Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesAreaLink__c/fields/mdr_Account__c.field-meta.xml
<CustomField>
    <fullName>mdr_Account__c</fullName>
    <description>Create connection between Sales Area Link and Account object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Areas</relationshipLabel>
    <relationshipName>SalesAreaLinks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesAreaLink__c/fields/mdr_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>mdr_SalesArea__c</fullName>
    <description>Create connection between Sales Area Link and Sales Area object</description>
    <label>Sales Area</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Sales Area Links</relationshipLabel>
    <relationshipName>SalesAreaLinks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/lkp_BillToAccount__c.field-meta.xml
<CustomField>
    <fullName>lkp_BillToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Bill-to Account)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/lkp_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>lkp_SalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SalesAreaLink__c.mdr_Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SalesAreaLink__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/lkp_ShipToAccount__c.field-meta.xml
<CustomField>
    <fullName>lkp_ShipToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship-to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Ship-to Account)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteValidateQuoteFieldsFlowTest.cls
/**
 * @description Test class for flw_Quote_BeforeCreate_PreFillFields flow
 * @author SNV1SF
 * @date 2026
 */


@isTest
public class QuoteValidateQuoteFieldsFlowTest {
        
@TestSetup  
     static void setupData() {  
    
         // Create a test Account
         Account account = (Account)TestFactory.createSObject(new Account(),'TestFactoryDefaults.AccountDefaults', true);    
         
         //Create Sales Area
         SalesArea__c salesArea = (SalesArea__c)TestFactory.createSObject(new SalesArea__c(),'TestFactoryDefaults.SalesAreaDefaults', true);
         
         // Create Sales Data Customer
         SalesAreaLink__c salesAreaLink = (SalesAreaLink__c)TestFactory.createSObject(new SalesAreaLink__c(),'TestFactoryDefaults.SalesAreaLinkDefaults', false);
         salesAreaLink.mdr_Account__c = account.Id;
         salesAreaLink.mdr_SalesArea__c = salesArea.Id;
         insert salesAreaLink;

         // Create Bosch Partner Functions
         BoschPartnerFunction__c billto = new BoschPartnerFunction__c();
         billto.Name ='Bill-to' ;
         billto.txt_PartnerFunction__c = 'BP';
         insert billto;
         
         BoschPartnerFunction__c shipto = new BoschPartnerFunction__c();
         shipto.Name ='Ship-to' ;
         shipto.txt_PartnerFunction__c = 'SH';
         insert shipto;
         
         //Create Bosch Partner: Partner Functions
         BoschPartner_PartnerFunction__c prf1 = new  BoschPartner_PartnerFunction__c();
         prf1.lkp_SalesDataCustomer__c = salesAreaLink.Id;
         prf1.mdr_BoschPartnerFunction__c = billto.Id;
         prf1.ReferencedAccount__c = account.Id;
         insert prf1;

         BoschPartner_PartnerFunction__c prf2 = new  BoschPartner_PartnerFunction__c();
         prf2.lkp_SalesDataCustomer__c = salesAreaLink.Id;
         prf2.mdr_BoschPartnerFunction__c = shipto.Id;
         prf2.ReferencedAccount__c = account.Id;
         insert prf2;

         // Create Opportunity
         Opportunity opp = (Opportunity)TestFactory.createSObject(new Opportunity(),'TestFactoryDefaults.OpportunityDefaults', false);
         opp.Name ='Test Opportunity for Quote PreFill fields';
         opp.AccountId = account.Id;
         opp.lkp_SalesDataCustomer__c = salesAreaLink.Id;      
         insert opp;
     }           

@isTest
static void validateCreateQuoteInheritOpportunityFields() {
      // Get records
        Account acc = [SELECT Id FROM Account LIMIT 1];    
        SalesAreaLink__c salesAreaLink = [SELECT Id FROM SalesAreaLink__c LIMIT 1 ];        
        Opportunity opp = [SELECT Id, CurrencyIsoCode, lkp_SalesDataCustomer__c  FROM Opportunity LIMIT 1 ];
        BoschPartnerFunction__c pfBill = [SELECT Id, Name FROM BoschPartnerFunction__c WHERE txt_PartnerFunction__c = 'BP' LIMIT 1 ];
        BoschPartnerFunction__c pfShip = [SELECT Id, Name FROM BoschPartnerFunction__c WHERE txt_PartnerFunction__c = 'SH' LIMIT 1 ];
        BoschPartner_PartnerFunction__c bill = [SELECT ReferencedAccount__c FROM  BoschPartner_PartnerFunction__c WHERE mdr_BoschPartnerFunction__c = :pfBill.Id AND lkp_SalesDataCustomer__c = :opp.lkp_SalesDataCustomer__c];
        BoschPartner_PartnerFunction__c ship = [SELECT ReferencedAccount__c FROM  BoschPartner_PartnerFunction__c WHERE mdr_BoschPartnerFunction__c = :pfShip.Id AND lkp_SalesDataCustomer__c = :opp.lkp_SalesDataCustomer__c];
               
        SBQQ__Quote__c quote =  new SBQQ__Quote__c();
        quote.SBQQ__Account__c = acc.Id;
        quote.SBQQ__Opportunity2__c = opp.Id;        
        quote.lkp_SalesArea__c = opp.lkp_SalesDataCustomer__c;
        quote.CurrencyIsoCode = opp.CurrencyIsoCode;
        quote.lkp_BillToAccount__c = bill.ReferencedAccount__c;
        quote.lkp_ShipToAccount__c = ship.ReferencedAccount__c;
        insert quote;
    
        Test.startTest();
             Database.SaveResult result = Database.insert(quote, false);  
        Test.stopTest();
    
        Assert.areEqual(quote.CurrencyIsoCode, opp.CurrencyIsoCode, 'The quote has the same currency as the related opportunity.');
        Assert.areEqual(quote.lkp_SalesArea__c, opp.lkp_SalesDataCustomer__c, 'The quote has the same Sales Area as the related opportunity.');
        Assert.areEqual(quote.lkp_BillToAccount__c, bill.ReferencedAccount__c, 'The Bill-to account on the quote is the same as the Referenced Account on Bosch Partner: Partner Function record for Bill-to partner function');
        Assert.areEqual(quote.lkp_ShipToAccount__c, ship.ReferencedAccount__c, 'The Ship-to account on the quote is the same as the Referenced Account on Bosch Partner: Partner Function record for Ship-to partner function');
       
    
}        
    
}