force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>false</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/lkp_SalesDataCustomer__c.field-meta.xml
<CustomField>
    <fullName>lkp_SalesDataCustomer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Structure sales based on a regional division of the market.</description>
    <label>Sales Data Customer</label>
    <referenceTo>SalesAreaLink__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pklLeadingSolutionField__c.field-meta.xml
<CustomField>
    <fullName>pklLeadingSolutionField__c</fullName>
    <label>Leading Solution Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DEV</fullName>
            </value>
            <value>
                <fullName>E2E</fullName>
            </value>
            <value>
                <fullName>MSS</fullName>
            </value>
            <value>
                <fullName>SEC</fullName>
            </value>
            <value>
                <fullName>VCS</fullName>
            </value>
            <value>
                <fullName>VOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pklTypeOfOffering__c.field-meta.xml
<CustomField>
    <fullName>pklTypeOfOffering__c</fullName>
    <label>Type of Offering</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SW</fullName>
            </value>
            <value>
                <fullName>HW</fullName>
            </value>
            <value>
                <fullName>ENG</fullName>
            </value>
            <value>
                <fullName>SRV​</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pklTypeOfOpportunity__c.field-meta.xml
<CustomField>
    <fullName>pklTypeOfOpportunity__c</fullName>
    <label>Type of Opportunity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LTA</fullName>
                <label>Long Term Agreement</label>
            </value>
            <value>
                <fullName>LTE</fullName>
                <label>Long Term Extension</label>
            </value>
            <value>
                <fullName>BCO</fullName>
                <label>Base Case Opportunity</label>
            </value>
            <value>
                <fullName>ACQ</fullName>
                <label>Acquisition Project</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce CPQ/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <description>Structure sales based on a regional division of the market.</description>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{000}</displayFormat>
        <label>Sales Area</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesArea__c/fields/pkl_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>pkl_DistributionChannel__c</fullName>
    <description>Distinguish different sales methods</description>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>gpkv_DistributionChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesArea__c/fields/pkl_Division__c.field-meta.xml
<CustomField>
    <fullName>pkl_Division__c</fullName>
    <description>Represent ETAS Solution Fields</description>
    <label>Division</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>gpkv_Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesArea__c/fields/pkl_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>pkl_SalesOrg__c</fullName>
    <description>Structure sales based on a regional division of the market</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>gpkv_SalesOrg</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesAreaLink__c/SalesAreaLink__c.object-meta.xml
<CustomObject>
    <description>Establishes n:m relation between Sales Area and Account.</description>
    <label>Sales Area Link</label>
    <nameField>
        <displayFormat>SAL-{000000}</displayFormat>
        <label>Sales Area Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesAreaLink__c/fields/mdr_Account__c.field-meta.xml
<CustomField>
    <fullName>mdr_Account__c</fullName>
    <description>Create connection between Sales Area Link and Account object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Areas</relationshipLabel>
    <relationshipName>SalesAreaLinks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesAreaLink__c/fields/mdr_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>mdr_SalesArea__c</fullName>
    <description>Create connection between Sales Area Link and Sales Area object</description>
    <label>Sales Area</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Sales Area Links</relationshipLabel>
    <relationshipName>SalesAreaLinks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Number of quote for which the approval request is generated.</description>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__ApprovedBy__c.field-meta.xml
<CustomField>
    <fullName>sbaa__ApprovedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who approved this Approval</description>
    <inlineHelpText>User who approved this Approval</inlineHelpText>
    <label>Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApprovedApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Approver associated with this Approval.</description>
    <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
    <label>Approver</label>
    <referenceTo>sbaa__Approver__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>sbaa__AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the User to which the Approval is assigned</description>
    <inlineHelpText>Lookup to the User to which the Approval is assigned</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__CommentsLong__c.field-meta.xml
<CustomField>
    <fullName>sbaa__CommentsLong__c</fullName>
    <description>Approver&#39;s Comments</description>
    <inlineHelpText>Approver&#39;s Comments</inlineHelpText>
    <label>Comments</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__RejectedBy__c.field-meta.xml
<CustomField>
    <fullName>sbaa__RejectedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who rejected this Approval</description>
    <inlineHelpText>User who rejected this Approval</inlineHelpText>
    <label>Rejected By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RejectedApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Status__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Status__c</fullName>
    <description>Status of this approval.</description>
    <inlineHelpText>Status of this approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sbaa__Approver__c/sbaa__Approver__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approver__c/fields/sbaa__User__c.field-meta.xml
<CustomField>
    <fullName>sbaa__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If Approver is a single User, lookup to that User</description>
    <inlineHelpText>If Approver is a single User, lookup to that User</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/gpkv_DistributionChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A1</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <isActive>false</isActive>
        <label>01</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <isActive>false</isActive>
        <label>10</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <isActive>false</isActive>
        <label>11</label>
    </customValue>
    <customValue>
        <fullName>F0</fullName>
        <isActive>false</isActive>
        <label>Direct sales</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <isActive>false</isActive>
        <label>13</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <isActive>false</isActive>
        <label>14</label>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <isActive>false</isActive>
        <label>Z1</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <isActive>false</isActive>
        <label>12</label>
    </customValue>
    <customValue>
        <fullName>F1</fullName>
        <isActive>false</isActive>
        <label>Intercompany sales</label>
    </customValue>
    <description>Distinguish different sales methods</description>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/gpkv_Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>D0</fullName>
        <label>Reference Division</label>
    </customValue>
    <description>Represent ETAS Solution Fields
Division - D0</description>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/gpkv_SalesOrg.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DEM5</fullName>
    </customValue>
    <customValue>
        <fullName>USM5</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
        <isActive>false</isActive>
        <label>0003</label>
    </customValue>
    <customValue>
        <fullName>1010</fullName>
        <isActive>false</isActive>
        <label>1010</label>
    </customValue>
    <customValue>
        <fullName>1710</fullName>
        <isActive>false</isActive>
        <label>1710</label>
    </customValue>
    <customValue>
        <fullName>DE01</fullName>
        <isActive>false</isActive>
        <label>Sales Org. Germany</label>
    </customValue>
    <customValue>
        <fullName>PT01</fullName>
        <isActive>false</isActive>
        <label>PT01</label>
    </customValue>
    <customValue>
        <fullName>R000</fullName>
        <isActive>false</isActive>
        <label>R000</label>
    </customValue>
    <customValue>
        <fullName>ZZ11</fullName>
        <isActive>false</isActive>
        <label>ZZ11</label>
    </customValue>
    <customValue>
        <fullName>AOHU</fullName>
        <isActive>false</isActive>
        <label>AOHU</label>
    </customValue>
    <customValue>
        <fullName>US02</fullName>
        <isActive>false</isActive>
        <label>Sales Org. US</label>
    </customValue>
    <description>Structure sales based on a regional division of the market</description>
    <masterLabel>Sales Org</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ApprovalControllerTest.cls
/**
* @File Name : ApprovalControllerTest.cls
* @Description : Test class for ApprovalController
* @Author :
* @Last Modified By :
* @Last Modified On : November 4, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 4, 2025 |   | Initial Version
**/

@isTest
private class ApprovalControllerTest {
    
    @TestSetup
    static void setupTestData() {
        // Create test users and group in a separate context
        User testUser1;
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
            // Create test users
            
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
            
            testUser1 = (User)TestFactory.createSObject(new User(), 'TestFactoryDefaults.ProductManagerUserDefaults');
            testUser1.ProfileId = p.Id;
            testUser1.LastName = 'TestUser1';
            testUser1.Alias = 'tuser1';
            insert testUser1;
            
        }
        
        // Now create non-setup objects
        // Create Account (required for Quote)
        Account[] accountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        accountList[0].Name = 'TestAccount1'; 
        insert accountList;

        //Create Sales Area
         SalesArea__c sArea = (SalesArea__c)TestFactory.createSObject(new SalesArea__c());
            sArea.pkl_SalesOrg__c = 'DEM5';
            sArea.pkl_DistributionChannel__c ='	A1'; 
            sArea.pkl_Division__c = '01';
        insert sArea;
        
        //Create Sales Data Customer
        SalesAreaLink__c salesAreaLink = (SalesAreaLink__c)TestFactory.createSObject(new SalesAreaLink__c(),'TestFactoryDefaults.SalesAreaLinkDefaults', false);
        salesAreaLink.mdr_Account__c = accountList[0].Id;
        salesAreaLink.mdr_SalesArea__c = sArea.Id;
        insert salesAreaLink;
        
        //Create Opportunity (required for Quote)
        Opportunity opp = (Opportunity)TestFactory.createSObject(new Opportunity());
            opp.Name = 'Test Opportunity';
            opp.AccountId = accountList[0].Id;
            opp.StageName = 'Prospecting';
            opp.CloseDate = Date.today().addDays(30);
            opp.pklLeadingSolutionField__c = 'DEV';
            opp.pklTypeOfOpportunity__c = 'LTA';
            opp.pklTypeOfOffering__c = 'SW';
            opp.lkp_SalesDataCustomer__c = salesAreaLink.Id;
            insert opp;
        
        // Create Quote
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c[])TestFactory.createSObjectList(new SBQQ__Quote__c(), 1);
            quoteList[0].SBQQ__Opportunity2__c = opp.Id;
            quoteList[0].SBQQ__Account__c = accountList[0].Id;
        insert quoteList;
        
        // Re-query users to get their Ids
        testUser1 = [SELECT Id FROM User WHERE LastName = 'TestUser1' LIMIT 1];
        
        // Create Approvers
        sbaa__Approver__c approver1 = new sbaa__Approver__c(
            sbaa__User__c = testUser1.Id,
            Name = 'Test Approver 1'
        );
        insert approver1;
        
        // Create Approvals with different statuses
        List<sbaa__Approval__c> approvals = new List<sbaa__Approval__c>();
        
        // Pending approval for user approver
        approvals.add(new sbaa__Approval__c(
            sbaa__AssignedTo__c = testUser1.Id,
            sbaa__Approver__c = approver1.Id,
            sbaa__Status__c = 'Pending',
            sbaa__ApprovalStep__c = 1,
            sbaa__RecordField__c = 'Status',
            Quote__c = quoteList[0].Id
        ));        
        insert approvals;
        
        // update approval by approving
        sbaa__Approval__c updateApp = new sbaa__Approval__c();
        updateApp.Id = approvals[0].Id;
        updateApp.sbaa__Status__c = 'Approved';
        updateApp.sbaa__ApprovedBy__c = testUser1.Id;
        updateApp.sbaa__CommentsLong__c= 'This is approved';
        update updateApp;
    }
        
    @isTest
    static void testGetMyApprovals_UserApprover() {
        User testUser1 = [SELECT Id FROM User WHERE LastName = 'TestUser1' LIMIT 1];
        
        System.runAs(testUser1) {
            Test.startTest();
            List<sbaa__Approval__c> results = ApprovalController.getMyApprovals();
            Test.stopTest();
            
            // Should return only pending approvals (not approved/rejected)
            // User has 2 pending approvals (1 direct, 1 through group)
            System.assertEquals(0, results.size(), 'Should return 0 pending approvals');
            
            // Verify excluded statuses are not returned
            for (sbaa__Approval__c approval : results) {
                System.assertNotEquals('Approved', approval.sbaa__Status__c, 'Should not return approved');
                System.assertNotEquals('Rejected', approval.sbaa__Status__c, 'Should not return rejected');
            }
        }
    }
    
    @isTest
    static void testGetMyHistoryApprovals() {
        User testUser1 = [SELECT Id FROM User WHERE LastName = 'TestUser1' LIMIT 1];
        
        System.runAs(testUser1) {
            Test.startTest();
            List<sbaa__Approval__c> results = ApprovalController.getMyHistoryApprovals();
            Test.stopTest();
            
            // Should return 2 approvals (1 approved, 1 rejected by testUser1)
            System.assertEquals(1, results.size(), 'Should return 0 historical approvals');
            
            // Verify each approval has either approved or rejected by this user
            for (sbaa__Approval__c approval : results) {
                Boolean isApprovedByUser = (approval.sbaa__ApprovedBy__c == testUser1.Id);
                Boolean isRejectedByUser = (approval.sbaa__RejectedBy__c == testUser1.Id);
                System.assert(
                    isApprovedByUser || isRejectedByUser,
                    'Approval should be approved or rejected by current user'
                );
            }
        }
    }
}