force-app/main/default/objects/Account/fields/pkl_INCOTerms1__c.field-meta.xml
<CustomField>
    <fullName>pkl_INCOTerms1__c</fullName>
    <description>Defines the terms of sales and the passing of risks. Needed for the interface to ERP.</description>
    <label>INCOTERM</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>INCOTerms1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pkl_PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>pkl_PaymentTerms__c</fullName>
    <description>Defines which Payment Terms were negotiated with the customer. Needed for the interface to ERP.</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__PaymentTerm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/txt_INCOTerms2__c.field-meta.xml
<CustomField>
    <fullName>txt_INCOTerms2__c</fullName>
    <description>Defines at which location the INCO Terms will start.</description>
    <label>INCOTERM Location without Athena</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pklLeadingSolutionField__c.field-meta.xml
<CustomField>
    <fullName>pklLeadingSolutionField__c</fullName>
    <label>Leading Solution Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DEV</fullName>
            </value>
            <value>
                <fullName>E2E</fullName>
            </value>
            <value>
                <fullName>MSS</fullName>
            </value>
            <value>
                <fullName>SEC</fullName>
            </value>
            <value>
                <fullName>VCS</fullName>
            </value>
            <value>
                <fullName>VOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pklTypeOfOffering__c.field-meta.xml
<CustomField>
    <fullName>pklTypeOfOffering__c</fullName>
    <label>Type of Offering</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SW</fullName>
            </value>
            <value>
                <fullName>HW</fullName>
            </value>
            <value>
                <fullName>ENG</fullName>
            </value>
            <value>
                <fullName>SRV​</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pklTypeOfOpportunity__c.field-meta.xml
<CustomField>
    <fullName>pklTypeOfOpportunity__c</fullName>
    <label>Type of Opportunity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LTA</fullName>
                <label>Long Term Agreement</label>
            </value>
            <value>
                <fullName>LTE</fullName>
                <label>Long Term Extension</label>
            </value>
            <value>
                <fullName>BCO</fullName>
                <label>Base Case Opportunity</label>
            </value>
            <value>
                <fullName>ACQ</fullName>
                <label>Acquisition Project</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/pkl_SolutionField__c.field-meta.xml
<CustomField>
    <fullName>pkl_SolutionField__c</fullName>
    <description>Specifies the product being upgraded.</description>
    <label>Solution Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DEV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/pkl_INCOTerms1__c.field-meta.xml
<CustomField>
    <fullName>pkl_INCOTerms1__c</fullName>
    <description>Defines the terms of sales and the passing of risks. Needed for the interface to ERP.</description>
    <inlineHelpText>Defines the terms of sales and the passing of risks. Needed for the interface to ERP.Defines the terms of sales and the passing of risks. Needed for the interface to ERP.</inlineHelpText>
    <label>INCO Terms 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>INCOTerms1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/pkl_PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>pkl_PaymentTerms__c</fullName>
    <description>Defines which Payment Terms were negotiated with the customer. Needed for the interface to ERP.</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__PaymentTerm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/txt_INCOTerms2__c.field-meta.xml
<CustomField>
    <fullName>txt_INCOTerms2__c</fullName>
    <description>Defines at which location the INCO Terms will start.</description>
    <label>INCO Terms 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ftxt_ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>ftxt_ShortDescription__c</fullName>
    <description>A field that allows to display short product description from Product object</description>
    <formula>SBQQ__Product__r.txa_ShortDescription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Short Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/pkl_INCOTerms1__c.field-meta.xml
<CustomField>
    <fullName>pkl_INCOTerms1__c</fullName>
    <description>Defines the terms of sales and the passing of risks. Needed for the interface to ERP.Defines the terms of sales and the passing of risks. Needed for the interface to ERP.</description>
    <label>INCOTERM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>INCOTerms1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/pkl_PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>pkl_PaymentTerms__c</fullName>
    <description>Defines which Payment Terms were negotiated with the customer. Needed for the interface to ERP.</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__PaymentTerm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/pkl_QuantityUnit__c.field-meta.xml
<CustomField>
    <fullName>pkl_QuantityUnit__c</fullName>
    <description>Defines which unit of measure the product describes. Needed for the interface to ERP.</description>
    <label>Quantity Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuantityUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/pkl_SolutionField__c.field-meta.xml
<CustomField>
    <fullName>pkl_SolutionField__c</fullName>
    <label>Solution Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DEV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/txt_INCOTerms2__c.field-meta.xml
<CustomField>
    <fullName>txt_INCOTerms2__c</fullName>
    <description>Defines at which location the INCO Terms will start.</description>
    <label>INCOTERM Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/INCOTerms1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFR - Cost and Freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIF - Cost, Insurance, and Freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIP - Carriage and Insurance Paid To</fullName>
    </customValue>
    <customValue>
        <fullName>CPT - Carriage Paid To</fullName>
    </customValue>
    <customValue>
        <fullName>DAP – Delivered at Place</fullName>
    </customValue>
    <customValue>
        <fullName>DAT- Delivery at Terminal</fullName>
    </customValue>
    <customValue>
        <fullName>DDP - Delivered Duty Paid</fullName>
    </customValue>
    <customValue>
        <fullName>DPU-Delivered at Place Unloaded</fullName>
    </customValue>
    <customValue>
        <fullName>EXW - Ex Works</fullName>
    </customValue>
    <customValue>
        <fullName>FAS - Free Alongside Ship</fullName>
    </customValue>
    <customValue>
        <fullName>FCA - Free Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>FOB - Free On Board ship</fullName>
    </customValue>
    <customValue>
        <fullName>DDU - Delivered Duty Unpaid</fullName>
        <isActive>false</isActive>
        <label>DDU - Delivered Duty Unpaid</label>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
        <isActive>false</isActive>
        <label>DAP</label>
    </customValue>
    <customValue>
        <fullName>DAF - Delivered At Frontier</fullName>
        <isActive>false</isActive>
        <label>DAF - Delivered At Frontier</label>
    </customValue>
    <customValue>
        <fullName>FCA - Free Carriage and Freight</fullName>
        <isActive>false</isActive>
        <label>FCA - Free Carriage and Freight</label>
    </customValue>
    <customValue>
        <fullName>DES - Delivered Ex Ship</fullName>
        <isActive>false</isActive>
        <label>DES - Delivered Ex Ship</label>
    </customValue>
    <customValue>
        <fullName>DEQ - Delivered Ex Quay</fullName>
        <isActive>false</isActive>
        <label>DEQ - Delivered Ex Quay</label>
    </customValue>
    <description>Picklist to store possible INCO Terms values, used in S4/Hana. Needed on several objects for the interface.</description>
    <masterLabel>INCO Terms 1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/QuantityUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>KG</fullName>
        <default>true</default>
        <label>KG</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <masterLabel>Quantity Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SBQQ__PaymentTerm.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Due on receipt</fullName>
    </customValue>
    <customValue>
        <fullName>Net 15</fullName>
    </customValue>
    <customValue>
        <fullName>Net 30</fullName>
    </customValue>
    <customValue>
        <fullName>Net 45</fullName>
    </customValue>
    <customValue>
        <fullName>Net 60</fullName>
    </customValue>
    <customValue>
        <fullName>Net 90</fullName>
    </customValue>
    <masterLabel>Payment Term</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteLineEmailController_Test.cls
@isTest
public class QuoteLineEmailController_Test {	
    
    @isTest
    static void testQuoteLineEmailController() {
        // Create a test Account using TestFactory
        Account[] testAccountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        insert testAccountList;
        Account testAccount = testAccountList[0];
        
        // Create a test Opportunity using TestFactory
            Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity', 
            AccountId = testAccount.Id, 
            StageName = 'Prospecting', 
            CloseDate = Date.today().addDays(30),
            pklTypeOfOpportunity__c = 'LTA',
            pklLeadingSolutionField__c = 'DAP',
            pklTypeOfOffering__c = 'SW'
        );
        insert testOpportunity;
        
        // Create a test Quote using TestFactory
        SBQQ__Quote__c[] testQuoteList = (SBQQ__Quote__c[])TestFactory.createSObjectList(new SBQQ__Quote__c(), 1);
        testQuoteList[0].SBQQ__Opportunity2__c = testOpportunity.Id; // Set the Opportunity relationship
        insert testQuoteList;
        SBQQ__Quote__c testQuote = testQuoteList[0];
        
        // Create a test Product using TestFactory
        Product2[] testProductList = (Product2[])TestFactory.createSObjectList(new Product2(), 1);
        insert testProductList;
        Product2 testProduct = testProductList[0];
        
        // Create test QuoteLine records using TestFactory
        SBQQ__QuoteLine__c[] quoteLinesList = (SBQQ__QuoteLine__c[])TestFactory.createSObjectList(new SBQQ__QuoteLine__c(), 5);
        for (Integer i = 0; i < quoteLinesList.size(); i++) {
            quoteLinesList[i].SBQQ__Quote__c = testQuote.Id;
            quoteLinesList[i].SBQQ__Product__c = testProduct.Id;
            quoteLinesList[i].pkl_SolutionField__c = 'DEV';
            quoteLinesList[i].pkl_QuantityUnit__c = 'Month';
            quoteLinesList[i].pkl_INCOTerms1__c = 'DAP – Delivered at Place';
            quoteLinesList[i].txt_INCOTerms2__c = 'Inco Terms';
            quoteLinesList[i].pkl_PaymentTerms__c = 'Net 15';
        }
        insert quoteLinesList;
        
        // Initialize the QuoteLineEmailController with the quote ID
        QuoteLineEmailController controller = new QuoteLineEmailController();
        controller.quoteIdParam = testQuote.Id;
        
        // Test that the quoteLineItems are populated correctly
        List<SBQQ__QuoteLine__c> resultQuoteLines = controller.quoteLineItems;
        
        // Assert that the quoteLineItems list is not empty
        System.assertNotEquals(resultQuoteLines.size(), 0, 'QuoteLineItems should not be empty.');
        
        // Assert that the number of quote lines returned matches what was inserted
        System.assertEquals(resultQuoteLines.size(), 5, 'The number of QuoteLineItems should be 5.');
        
        // You can also assert that the expected field values are correct
        SBQQ__QuoteLine__c firstQuoteLine = resultQuoteLines[0];
        //System.assertEquals(firstQuoteLine.SBQQ__Product__r.Name, 'Test Product', 'The Product name should match.');
        //System.assertEquals(firstQuoteLine.SBQQ__Quantity__c, 10, 'The quantity should match.');
        //System.assertEquals(firstQuoteLine.ftxt_ShortDescription__c, 'Description 0', 'The short description should match.');
    }
}