force-app/main/default/objects/Account/fields/pkl_AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>pkl_AccountGroup__c</fullName>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YDE1</fullName>
            </value>
            <value>
                <fullName>YCN1</fullName>
            </value>
            <value>
                <fullName>YJP1</fullName>
            </value>
            <value>
                <fullName>YOM1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pkl_Language__c.field-meta.xml
<CustomField>
    <fullName>pkl_Language__c</fullName>
    <description>Language options for account</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pkl_Status__c.field-meta.xml
<CustomField>
    <fullName>pkl_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Sent to Athena</fullName>
            </value>
            <value>
                <fullName>Error in sending to Athena</fullName>
            </value>
            <value>
                <fullName>Received in Athena for BP creation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/mpkl_RoleMainAccount__c.field-meta.xml
<CustomField>
    <fullName>mpkl_RoleMainAccount__c</fullName>
    <label>Role Main Account</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>gpkv_ContactRoles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pkl_AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>pkl_AccountGroup__c</fullName>
    <label>Account Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ETDE Contact ETCN Contact</fullName>
            </value>
            <value>
                <fullName>ETJP Contact</fullName>
            </value>
            <value>
                <fullName>ETKR Contact</fullName>
            </value>
            <value>
                <fullName>ETNA - OEM/Fleet Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pkl_Language__c.field-meta.xml
<CustomField>
    <fullName>pkl_Language__c</fullName>
    <description>Contact&#39;s primary language</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pkl_Status__c.field-meta.xml
<CustomField>
    <fullName>pkl_Status__c</fullName>
    <description>Contact Status in Athena System, describes whether the Person Business Partner is aligned in Athena or Not</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOSCH_PARTNER_NUMBER_NOT_RECEIVED</fullName>
                <label>Bosch Partner Number not Received</label>
            </value>
            <value>
                <fullName>CREATED_IN_ATHENA</fullName>
                <label>Created in Athena</label>
            </value>
            <value>
                <fullName>DRAFT</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>ERROR_IN_SENDING_TO_ATHENA</fullName>
                <label>Error in sending to Athena</label>
            </value>
            <value>
                <fullName>RECEIVED_IN_ATHENA_FOR_BP_CREATION</fullName>
                <label>Received in Athena for BP creation</label>
            </value>
            <value>
                <fullName>SENT_TO_ATHENA</fullName>
                <label>Sent to Athena</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/pkl_Status__c.field-meta.xml
<CustomField>
    <fullName>pkl_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>init</fullName>
            </value>
            <value>
                <fullName>Send to Sign</fullName>
                <isActive>false</isActive>
                <label>Send to Sign</label>
            </value>
            <value>
                <fullName>Signed</fullName>
                <isActive>false</isActive>
                <label>Signed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Docusign_Setting__mdt/Docusign_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Docusign Setting</label>
    <pluralLabel>Docusign Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Docusign_Setting__mdt/fields/accountId__c.field-meta.xml
<CustomField>
    <fullName>accountId__c</fullName>
    <label>accountId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docusign_Setting__mdt/fields/audience__c.field-meta.xml
<CustomField>
    <fullName>audience__c</fullName>
    <label>audience</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docusign_Setting__mdt/fields/baseUrl__c.field-meta.xml
<CustomField>
    <fullName>baseUrl__c</fullName>
    <label>baseUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Docusign_Setting__mdt/fields/certificateName__c.field-meta.xml
<CustomField>
    <fullName>certificateName__c</fullName>
    <label>certificate Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docusign_Setting__mdt/fields/userId__c.field-meta.xml
<CustomField>
    <fullName>userId__c</fullName>
    <label>userId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/gpkv_ContactRoles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0001</fullName>
        <label>Director</label>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
        <label>Accounting clerk</label>
    </customValue>
    <masterLabel>Contact Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese trad.</fullName>
    </customValue>
    <customValue>
        <fullName>Croatian</fullName>
    </customValue>
    <customValue>
        <fullName>Customer reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Finnish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Hebrew</fullName>
    </customValue>
    <customValue>
        <fullName>Hindi</fullName>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
    </customValue>
    <customValue>
        <fullName>Icelandic</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Kazakh</fullName>
    </customValue>
    <customValue>
        <fullName>Korean</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Malay</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/tests/DocusignService_Test.cls
@isTest
public class DocusignService_Test {

    @testSetup
    public static void initRecords(){
        
        Account[] testAccountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        insert testAccountList;

        Contact[] testContactList = (Contact[])TestFactory.createSObjectList(new Contact(), 1);
        testContactList[0].AccountId = testAccountList[0].Id;
        testContactList[0].mpkl_RoleMainAccount__c = '0001';
        testContactList[0].pkl_Language__c = 'English';
        testContactList[0].pkl_Status__c = 'Active';
        testContactList[0].Email = 'testEmail@invalid.com';
        testContactList[0].pkl_AccountGroup__c = 'ETDE Contact ETCN Contact';

        insert testContactList;
        
        ContentVersion[] contentVersionList = (ContentVersion[])TestFactory.createSObjectList(new ContentVersion(), 1);
        contentVersionList[0].IsMajorVersion = true; 
        insert contentVersionList;
        ContentVersion contentVersion = contentVersionList[0];
        
        // Get the ContentDocumentId - same as original
        contentVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id LIMIT 1];
        Id contentDocumentId = contentVersion.ContentDocumentId;
        
        // Create ContentDocumentLink using TestFactory
        // This should use ContentDocumentLinkDefaults from your TestFactoryDefaults class
        ContentDocumentLink[] linkList = (ContentDocumentLink[])TestFactory.createSObjectList(new ContentDocumentLink(), 1);
        linkList[0].ContentDocumentId = contentDocumentId; // Set the dynamic fields
        linkList[0].LinkedEntityId = testAccountList[0].Id;
        linkList[0].ShareType = 'V'; // This should come from defaults, but set explicitly
        insert linkList;
        
    }
    
    @isTest
    public static void sendEnvelope(){
        Docusign_Setting__mdt config = [SELECT clientId__c, userId__c, audience__c, certificateName__c,DeveloperName, accountId__c, baseUrl__c FROM Docusign_Setting__mdt WITH USER_MODE LIMIT 1];
        
        StaticResource sr2 = [SELECT Body FROM StaticResource WHERE Name = 'getAccessTokenBody'];
		String tokenBody = sr2.Body.toString();

        HTTPMockGenerator res2 = new HTTPMockGenerator(200, tokenBody);

        Test.setMock(HttpCalloutMock.class, res2);
        DocusignService docusignService= new DocuSignService(config.DeveloperName);
        
        ContentVersion cv = [SELECT Id,VersionData from ContentVersion LIMIT 1];
        ContentDocument cd = [Select Id,Title from ContentDocument LIMIT 1];
        Contact cont = [Select Id,Email from Contact LIMIT 1];

        Assert.areNotEqual(null, cd, 'The document is not null');
        Blob myPdfBlob = cv.VersionData;
        String base64Doc = EncodingUtil.base64Encode(myPdfBlob);
        Test.startTest();
        String result = docusignService.sendEnvelope(
            cont.Email,
            cont.Email,
            base64Doc,
            cd.Title
        );
        Test.stopTest();
    }
    
    @isTest
    public static void getSignedDocument(){
        
        StaticResource sr2 = [SELECT Body FROM StaticResource WHERE Name = 'getAccessTokenBody'];
		String tokenBody = sr2.Body.toString();

        HTTPMockGenerator res2 = new HTTPMockGenerator(200, tokenBody);

        Test.setMock(HttpCalloutMock.class, res2);
        DocuSignService service = new DocuSignService('Docusign_Service');
     	ContentDocument cd = [Select Id,Title from ContentDocument LIMIT 1];
        Test.startTest();
        Blob document = service.getSignedDocument('2131232312434546', 'combined');
        Assert.areNotEqual(null, document, 'The document is not null');
        Test.stopTest();
    }
    
    @isTest
    public static void getDocumentsById(){
        List<Id> listDocumentIds= new List<Id>();
        ContentDocument cd = [Select Id,Title from ContentDocument LIMIT 1];
     	ContentVersion cv = [SELECT Id,VersionData,ContentDocumentId from ContentVersion LIMIT 1];
        ContentDocumentLink cdl = [SELECT Id,ContentDocumentId,LinkedEntityId,ShareType from ContentDocumentLink WHERE ContentDocumentId=: cd.Id LIMIT 1];
        listDocumentIds.add(cdl.Id);
        Assert.areNotEqual(null, listDocumentIds, 'The list of documents is not null');
        Test.startTest();
        DocuSignService.getDocumentsbyId(listDocumentIds);
        Test.stopTest();
    }
}