force-app/main/default/objects/Account/fields/pkl_AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>pkl_AccountGroup__c</fullName>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YDE1</fullName>
            </value>
            <value>
                <fullName>YCN1</fullName>
            </value>
            <value>
                <fullName>YJP1</fullName>
            </value>
            <value>
                <fullName>YOM1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pkl_Language__c.field-meta.xml
<CustomField>
    <fullName>pkl_Language__c</fullName>
    <description>Language options for account</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pkl_Status__c.field-meta.xml
<CustomField>
    <fullName>pkl_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Sent to Athena</fullName>
            </value>
            <value>
                <fullName>Error in sending to Athena</fullName>
            </value>
            <value>
                <fullName>Received in Athena for BP creation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/mpkl_PartnerRoles__c.field-meta.xml
<CustomField>
    <fullName>mpkl_PartnerRoles__c</fullName>
    <label>Partner Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>gpkv_ContactRoles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/mpkl_RoleMainAccount__c.field-meta.xml
<CustomField>
    <fullName>mpkl_RoleMainAccount__c</fullName>
    <label>Role Main Account</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>gpkv_ContactRoles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pkl_AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>pkl_AccountGroup__c</fullName>
    <label>Account Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ETDE Contact ETCN Contact</fullName>
            </value>
            <value>
                <fullName>ETJP Contact</fullName>
            </value>
            <value>
                <fullName>ETKR Contact</fullName>
            </value>
            <value>
                <fullName>ETNA - OEM/Fleet Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pkl_Language__c.field-meta.xml
<CustomField>
    <fullName>pkl_Language__c</fullName>
    <description>Contact&#39;s primary language</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pkl_Status__c.field-meta.xml
<CustomField>
    <fullName>pkl_Status__c</fullName>
    <description>Contact Status in Athena System, describes whether the Person Business Partner is aligned in Athena or Not</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOSCH_PARTNER_NUMBER_NOT_RECEIVED</fullName>
                <label>Bosch Partner Number not Received</label>
            </value>
            <value>
                <fullName>CREATED_IN_ATHENA</fullName>
                <label>Created in Athena</label>
            </value>
            <value>
                <fullName>DRAFT</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>ERROR_IN_SENDING_TO_ATHENA</fullName>
                <label>Error in sending to Athena</label>
            </value>
            <value>
                <fullName>RECEIVED_IN_ATHENA_FOR_BP_CREATION</fullName>
                <label>Received in Athena for BP creation</label>
            </value>
            <value>
                <fullName>SENT_TO_ATHENA</fullName>
                <label>Sent to Athena</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/gpkv_ContactRoles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0001</fullName>
        <label>Director</label>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
        <label>Accounting clerk</label>
    </customValue>
    <masterLabel>Contact Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese trad.</fullName>
    </customValue>
    <customValue>
        <fullName>Croatian</fullName>
    </customValue>
    <customValue>
        <fullName>Customer reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Finnish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Hebrew</fullName>
    </customValue>
    <customValue>
        <fullName>Hindi</fullName>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
    </customValue>
    <customValue>
        <fullName>Icelandic</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Kazakh</fullName>
    </customValue>
    <customValue>
        <fullName>Korean</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Malay</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/tests/ContactBeforeUpdateTest.cls
/**
* @author       APB
* @description  ContactBeforeUpdateTest: Class used to test the flow propagate main contact before update
*/
@isTest
public class ContactBeforeUpdateTest {

    /**
    * @author       APB
    * @description  Method used to create the records
    */
    @testSetup
    public static void createRecords(){

        Account[] testAccountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
            insert testAccountList;

            Contact[] testContactList = (Contact[])TestFactory.createSObjectList(new Contact(), 1);
            testContactList[0].AccountId = testAccountList[0].Id;
            testContactList[0].mpkl_RoleMainAccount__c = '0001';
            testContactList[0].pkl_Language__c = 'English';
            testContactList[0].pkl_Status__c = 'Active';
            testContactList[0].pkl_AccountGroup__c = 'ETDE Contact ETCN Contact';

            insert testContactList;
    }


    @IsTest
    public static void succesfullUpdateOfRoleMainAccountField(){
        User productManagerUser = (User)TestFactory.createSObject(new User(), 'TestFactoryDefaults.ProductManagerUserDefaults', true);
        Account testAccount = [Select Id from Account LIMIT 1];
        Contact testContact = [Select Id from Contact LIMIT 1];
        System.runAs(productManagerUser){

            AccountContactRelation acr = [Select Id,mpkl_PartnerRoles__c from AccountContactRelation WHERE ContactId =: testContact.Id AND AccountId =: testAccount.Id LIMIT 1];
            Assert.areEqual('0001', acr.mpkl_PartnerRoles__c, 'Role should be 0001');

            testContact.mpkl_RoleMainAccount__c = '0003;0001;';
            update testContact;

            AccountContactRelation acrModified = [Select Id,mpkl_PartnerRoles__c from AccountContactRelation WHERE ContactId =: testContact.Id AND AccountId =: testAccount.Id LIMIT 1];
            Assert.areEqual('0001;0003', acrModified.mpkl_PartnerRoles__c, 'Role should be 0001;0003');
        }
    }

    @IsTest
    public static void incorrectUpdateOfRoleMainAccountField(){
        User productManagerUser = (User)TestFactory.createSObject(new User(), 'TestFactoryDefaults.ProductManagerUserDefaults', true);
        System.runAs(productManagerUser){

            Account testAccount = [Select Id from Account LIMIT 1];
            Contact testContact = [Select Id from Contact LIMIT 1];

            AccountContactRelation acr = [Select Id,mpkl_PartnerRoles__c from AccountContactRelation WHERE ContactId =: testContact.Id AND AccountId =: testAccount.Id LIMIT 1];
            Assert.areEqual('0001', acr.mpkl_PartnerRoles__c, 'Role should be 0001');

            testContact.mpkl_RoleMainAccount__c = '0003;0001;';
            update testContact;

            AccountContactRelation acrModified = [Select Id,mpkl_PartnerRoles__c from AccountContactRelation WHERE ContactId =: testContact.Id AND AccountId =: testAccount.Id LIMIT 1];
            Assert.areNotEqual('0001', acrModified.mpkl_PartnerRoles__c, 'Incorrect data, the role should be 0001;0003');
        }
    }

}