force-app/main/default/objects/Account/fields/pkl_INCOTerms1__c.field-meta.xml
<CustomField>
    <fullName>pkl_INCOTerms1__c</fullName>
    <description>Defines the terms of sales and the passing of risks. Needed for the interface to ERP.</description>
    <label>INCOTERM</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>INCOTerms1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pkl_Language__c.field-meta.xml
<CustomField>
    <fullName>pkl_Language__c</fullName>
    <description>Language options for account</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pkl_PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>pkl_PaymentTerms__c</fullName>
    <description>Defines which Payment Terms were negotiated with the customer. Needed for the interface to ERP.</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__PaymentTerm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pkm_BoschPartnerRole__c.field-meta.xml
<CustomField>
    <fullName>pkm_BoschPartnerRole__c</fullName>
    <label>Bosch Partner Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BBCUEX</fullName>
            </value>
            <value>
                <fullName>BBCUSH</fullName>
            </value>
            <value>
                <fullName>BBCUBP</fullName>
            </value>
            <value>
                <fullName>BBCUPR</fullName>
            </value>
            <value>
                <fullName>Bill-to</fullName>
                <isActive>false</isActive>
                <label>Bill-to</label>
            </value>
            <value>
                <fullName>Ship-to</fullName>
                <isActive>false</isActive>
                <label>Ship-to</label>
            </value>
            <value>
                <fullName>Sold-to</fullName>
                <isActive>false</isActive>
                <label>Sold-to</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Used by Sales Team to determine the role of the customer and which territory it belongs to</description>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ETDE Domestic Customer</fullName>
            </value>
            <value>
                <fullName>ETUS Domestic Customer</fullName>
            </value>
            <value>
                <fullName>ETCN Domestic Customer</fullName>
            </value>
            <value>
                <fullName>ETJP Domestic Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/txt_INCOTerms2__c.field-meta.xml
<CustomField>
    <fullName>txt_INCOTerms2__c</fullName>
    <description>Defines at which location the INCO Terms will start.</description>
    <label>INCOTERM Location without Athena</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>false</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Contact/fields/pkl_Language__c.field-meta.xml
<CustomField>
    <fullName>pkl_Language__c</fullName>
    <description>Contact&#39;s primary language</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/INCOTerms1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFR - Cost and Freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIF - Cost, Insurance, and Freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIP - Carriage and Insurance Paid To</fullName>
    </customValue>
    <customValue>
        <fullName>CPT - Carriage Paid To</fullName>
    </customValue>
    <customValue>
        <fullName>DAP – Delivered at Place</fullName>
    </customValue>
    <customValue>
        <fullName>DAT- Delivery at Terminal</fullName>
    </customValue>
    <customValue>
        <fullName>DDP - Delivered Duty Paid</fullName>
    </customValue>
    <customValue>
        <fullName>DPU-Delivered at Place Unloaded</fullName>
    </customValue>
    <customValue>
        <fullName>EXW - Ex Works</fullName>
    </customValue>
    <customValue>
        <fullName>FAS - Free Alongside Ship</fullName>
    </customValue>
    <customValue>
        <fullName>FCA - Free Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>FOB - Free On Board ship</fullName>
    </customValue>
    <customValue>
        <fullName>DDU - Delivered Duty Unpaid</fullName>
        <isActive>false</isActive>
        <label>DDU - Delivered Duty Unpaid</label>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
        <isActive>false</isActive>
        <label>DAP</label>
    </customValue>
    <customValue>
        <fullName>DAF - Delivered At Frontier</fullName>
        <isActive>false</isActive>
        <label>DAF - Delivered At Frontier</label>
    </customValue>
    <customValue>
        <fullName>FCA - Free Carriage and Freight</fullName>
        <isActive>false</isActive>
        <label>FCA - Free Carriage and Freight</label>
    </customValue>
    <customValue>
        <fullName>DES - Delivered Ex Ship</fullName>
        <isActive>false</isActive>
        <label>DES - Delivered Ex Ship</label>
    </customValue>
    <customValue>
        <fullName>DEQ - Delivered Ex Quay</fullName>
        <isActive>false</isActive>
        <label>DEQ - Delivered Ex Quay</label>
    </customValue>
    <description>Picklist to store possible INCO Terms values, used in S4/Hana. Needed on several objects for the interface.</description>
    <masterLabel>INCO Terms 1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese trad.</fullName>
    </customValue>
    <customValue>
        <fullName>Croatian</fullName>
    </customValue>
    <customValue>
        <fullName>Customer reserve</fullName>
    </customValue>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Finnish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Hebrew</fullName>
    </customValue>
    <customValue>
        <fullName>Hindi</fullName>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
    </customValue>
    <customValue>
        <fullName>Icelandic</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Kazakh</fullName>
    </customValue>
    <customValue>
        <fullName>Korean</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Malay</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SBQQ__PaymentTerm.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Due on receipt</fullName>
    </customValue>
    <customValue>
        <fullName>Net 15</fullName>
    </customValue>
    <customValue>
        <fullName>Net 30</fullName>
    </customValue>
    <customValue>
        <fullName>Net 45</fullName>
    </customValue>
    <customValue>
        <fullName>Net 60</fullName>
    </customValue>
    <customValue>
        <fullName>Net 90</fullName>
    </customValue>
    <masterLabel>Payment Term</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Frameworks/TestFactory/TestFactoryDefaults.cls
/**
* @author       APC
* @date         08/04/2025
* @description  TestFactory framework: TestFactoryDefaults implements TestFactory
					To specify defaults for objects, use the naming convention [ObjectName]Defaults.
					For custom objects, omit the __c from the Object Name
*/
@IsTest
public with sharing class TestFactoryDefaults{

	/**
	* @author       APC
	* @description  AccountDefaults constructor
	*/
	public class AccountDefaults implements TestFactory.FieldDefaults {
		/**
		* @author       APC
		* @description  define account getFieldDefaults()
		* @return		Map<Schema.SObjectField, Object>
		*/
		public Map<Schema.SObjectField, Object> getFieldDefaults() {
			return new Map<Schema.SObjectField, Object> {
					Account.Name => 'Customer Account',
					Account.RecordTypeID => TestFactoryConstants.MAP_OBJ_RECORD_TYPE_IDS.get('Account').get('Customer'),
					Account.Phone => '0123456',
					Account.BillingCountry => 'bTest',
					Account.ShippingCountry => 'sTest',
					Account.txt_AthenaUUID__c => '1111',
					Account.Role__c => 'ETDE Domestic Customer',
					Account.pkl_INCOTerms1__c => 'CPT - Carriage Paid To',
					Account.pkl_PaymentTerms__c => 'Due on receipt',
					Account.txt_INCOTerms2__c => 'Inco terms 2 text area',
					Account.pkl_Language__c => 'English',
					Account.pkm_BoschPartnerRole__c => 'BBCUSH'
			};
		}
	}

	/**
	* @author       APC
	* @description  SupplierAccountDefault specific default set to be used in the future, be careful, 
						once this class will be changed, the test should be properly changed as well
	*/
	public class SupplierAccountDefault implements TestFactory.FieldDefaults {
		public Map<Schema.SObjectField, Object> getFieldDefaults() {
			return new Map<Schema.SObjectField, Object> {
					Account.Name => 'Supplier Account',
					Account.RecordTypeID => TestFactoryConstants.MAP_OBJ_RECORD_TYPE_IDS.get('Account').get('Supplier'),
					Account.Phone => '0123456',
					Account.txt_AthenaUUID__c => '2222',
					Account.Role__c => 'ETDE Domestic Customer',
					Account.pkl_INCOTerms1__c => 'CPT - Carriage Paid To',
					Account.pkl_PaymentTerms__c => 'Due on receipt',
					Account.txt_INCOTerms2__c => 'Inco terms 2 text area',
					Account.pkl_Language__c => 'English',
					Account.pkm_BoschPartnerRole__c => 'BBCUEX'
			};
		}
	}

	/**
	* @author       APC
	* @description  ContactDefaults constructor
	*/
	public class ContactDefaults implements TestFactory.FieldDefaults {
		/**
		* @author       APC
		* @description  define contact getFieldDefaults()
		* @return		Map<Schema.SObjectField, Object>
		*/
		public Map<Schema.SObjectField, Object> getFieldDefaults() {
			return new Map<Schema.SObjectField, Object> {
					Contact.FirstName => 'First',
					Contact.LastName => 'Last'
			};
		}
	}

	/**
	* @author       APC
	* @description  OpportunityDefault constructor
	*/
	public class OpportunityDefault implements TestFactory.FieldDefaults {
		/**
		* @author       APC
		* @description  define Opportunity getFieldDefaults()
		* @return		Map<Schema.SObjectField, Object>
		*/
		public Map<Schema.SObjectField, Object> getFieldDefaults() {
			return new Map<Schema.SObjectField, Object> {
					Opportunity.Name => 'Test Opportunity'
			};
		}
	}

	/**
	 * @author       APC
	 * @description  SalesReadUserDefaults constructor
	 */
	public class SalesReadUserDefaults implements TestFactory.FieldDefaults {
		/**
		 * @author       APC
		 * @description  define user getFieldDefaults()
		 * @return		Map<Schema.SObjectField, Object>
		 */
		public Map<Schema.SObjectField, Object> getFieldDefaults() {
			return new Map<Schema.SObjectField, Object>{
				User.Alias => 'userSalesRead',
				User.Email => 'testusuario1@example.com',
				User.Emailencodingkey => 'UTF-8',
				User.Languagelocalekey => 'en_US',
				User.Localesidkey => 'en_US',
				User.Profileid => TestFactoryConstants.MAP_PROFILE_IDS.get('SalesRead'),
				User.LastName => 'Sales Read',
				User.Country => 'United States',
				User.Timezonesidkey => 'America/Los_Angeles',
				User.FederationIdentifier => 'userSalesRead@etasbosch.com' + system.currentTimeMillis(),
				User.Username => 'userSalesRead@etasbosch.com' + system.currentTimeMillis()
			};
		}
	}

	/**
	 * @author       APC
	 * @description  ProductManagerUserDefaults constructor
	 */
	public class ProductManagerUserDefaults implements TestFactory.FieldDefaults {
		/**
		 * @author       APC
		 * @description  define user getFieldDefaults()
		 * @return		Map<Schema.SObjectField, Object>
		 */
		public Map<Schema.SObjectField, Object> getFieldDefaults() {
			return new Map<Schema.SObjectField, Object>{
				User.Alias => 'userPM',
				User.Email => 'testusuario1@example.com',
				User.Emailencodingkey => 'UTF-8',
				User.Languagelocalekey => 'en_US',
				User.Localesidkey => 'en_US',
				User.Profileid => TestFactoryConstants.MAP_PROFILE_IDS.get('ProductManager'),
				User.LastName => 'Test Back Office User',
				User.Country => 'United States',
				User.Timezonesidkey => 'America/Los_Angeles',
				User.FederationIdentifier => 'userPM@etasbosch.com' + system.currentTimeMillis(),
				User.Username => 'userPM@etasbosch.com' + system.currentTimeMillis()
			};
		}
	}

}	