force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Bill_To_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Country__c</fullName>
    <description>Contains Bill To Country information related to its respective Bill-to Account</description>
    <formula>lkp_BillToAccount__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bill_To_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Country__c</fullName>
    <description>Contains Bill To Country information related to its respective Bill-to Account</description>
    <formula>lkp_BillToAccount__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreditLimitCallouts.cls
public with sharing class CreditLimitCallouts {

    public static HttpResponse startVertexCallouts(Boolean isAccount, Boolean isQuote,Boolean isOrder,SBQQ__Quote__c quoteToCalculate,Order orderToCalculate){

        Http vertexHttp= new Http();
        HttpRequest vertexRequest = new HttpRequest();
        HttpResponse vertexResponse = new HttpResponse();    
            
        Date todayDate = Date.today();
        DateTime todayDateTime = DateTime.now();

        String remainingUrl = '/sap-tax-service/tax/v1/quote';

        vertexRequest.setEndpoint('callout:vertex_usernamePass'+ remainingUrl);
    
        vertexRequest.setHeader('Content-Type','application/json');

        vertexRequest.setMethod('POST');

        String finalVertexBody;
        
        if(isQuote && quoteToCalculate.SBQQ__Status__c == 'Accepted'){

            // Si no es accepted bloquearlo por js y ponerle un tooltip
            //  dto = new VertexBodyDTO(DateTime.now(), quoteToCalculate.Bill_To_Country__c);
            String bodyWrapper = JSON.serialize(VertexIntManager.createRequest(todayDateTime,quoteToCalculate.SBQQ__Account__r.BillingCountry));
            finalVertexBody = CreditLimitUtilMethods.formatRequest(bodyWrapper);
                
        }else if(isOrder && orderToCalculate.Status == 'Activated'){
                
        	String bodyWrapper = JSON.serialize(VertexIntManager.createRequest(todayDateTime,orderToCalculate.Account.BillingCountry));
            finalVertexBody = CreditLimitUtilMethods.formatRequest(bodyWrapper);
              
        }
        
        
        vertexRequest.setBody(finalVertexBody);

        List<SBQQ__Quote__c> listQuotesToUpdate = new List<SBQQ__Quote__c>();
        List<Order> listOrdersToUpdate = new List<Order>();

        System.debug(vertexRequest.getBody());
        vertexResponse = vertexHttp.send(vertexRequest);
        System.debug('aaaaa'+vertexResponse.getBody());
        
        return vertexResponse;
        
    }
    
    public static HttpResponse startCreditLimitCallouts(Boolean isAccount, Boolean isQuote,Boolean isOrder,String orgId,SBQQ__Quote__c quoteToCalculate,Order orderToCalculate,Account actualAccount){
        
        HttpResponse creditLimitResponse = new HttpResponse();
        HttpRequest request = new HttpRequest();
        Http creditLimitHttp= new Http();

        //    VertexMethods.wrapperResponse responseBody = new VertexMethods.wrapperResponse();
    
        request.setHeader('Content-Type','application/json');
        request.setHeader('accept','application/json');

        request.setMethod('POST');

      //  CreditLimitWrapperManager wrapperClass= new CreditLimitWrapperManager();
  
        // CreditLimit.wrapperResponse responseBody= new CreditLimit.wrapperResponse();

        String finalCreditLimitBody;

        if(isQuote && quoteToCalculate.SBQQ__Status__c == 'Accepted'){

        	request.setEndpoint('callout:creditLimitCheckOuathCallout');

            String bodyWrapper = JSON.serialize(CreditLimitWrapperManager.createCreditWorthinessRequest(orgId,quoteToCalculate.Current_Credit_Limit_including_VAT__c,quoteToCalculate.CurrencyIsoCode,quoteToCalculate.SBQQ__Account__r.txt_AthenaUUID__c ));
            finalCreditLimitBody= CreditLimitUtilMethods.formatRequest(bodyWrapper);
                
         }else if(isOrder && orderToCalculate.Status == 'Activated'){
             
         	 request.setEndpoint('callout:creditLimitCheckOuathCallout');
                
             String bodyWrapper = JSON.serialize(CreditLimitWrapperManager.createCreditWorthinessRequest(orgId,orderToCalculate.Current_Credit_Limit_including_VAT__c,orderToCalculate.CurrencyIsoCode,orderToCalculate.Account.txt_AthenaUUID__c));
              
             finalCreditLimitBody= CreditLimitUtilMethods.formatRequest(bodyWrapper);
              
         }else if(isAccount){   
             
         	request.setEndpoint('callout:creditLimitAccountOuathCallout');
                
            String bodyWrapper = JSON.serialize(CreditLimitWrapperManager.createAccountRequest(orgId,actualAccount.BillingCountry,actualAccount.txt_AthenaUUID__c));
              
            finalCreditLimitBody= CreditLimitUtilMethods.formatRequest(bodyWrapper);
             
         }
        
         request.setBody(finalCreditLimitBody);
      
         List<SBQQ__Quote__c> listQuotesToUpdate = new List<SBQQ__Quote__c>();
         List<Order> listOrdersToUpdate = new List<Order>();

         System.debug(request.getBody());
        
         // revisar si se puede hacer con el get status code
         if(request.getBody() != null && request.getBody() != ''){
             
         	creditLimitResponse = creditLimitHttp.send(request);
             
         }
        
        System.debug('responsee'+ creditLimitResponse.getBody());
         return creditLimitResponse;
            
    }
}