force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/cur_Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>cur_Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/tests/OrderSelectorTest.cls
@isTest
public class OrderSelectorTest {

    @testSetup
    static void initRecords(){

        Account[] testAccountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        testAccountList[0].CurrencyIsoCode = 'EUR';
        testAccountList[0].txt_AthenaUUID__c= '3123213';
        testAccountList[0].BillingCountry= 'Germany';
        testAccountList[0].BillingCountryCode= 'DE';
        insert testAccountList;
        
        Order[] orderList = (Order [])TestFactory.createSObjectList(new Order(),1);
        orderList[0].Status= 'Draft';
        orderList[0].AccountId= testAccountList[0].Id;
        insert orderList;
        
    }
    
    @isTest
    static void getOrder(){
        
        Set<Id> idSet = new Set<Id>();
        Test.startTest();
        Order orderTest = [SELECT Id,Status,cur_Current_Credit_Limit_including_VAT__c,CurrencyIsoCode,Account.txt_AthenaUUID__c from Order LIMIT 1];
		idSet.add(orderTest.Id);        
        OrderSelector os = new OrderSelector();
        List<Order> selectOrder = os.selectOrderInfo(idSet);
        Assert.areNotEqual(null, selectOrder[0], 'The quote was retrieved succesfully');
        Test.stopTest();
    }
    
}