force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Apttus__Agreement_Clause__c/Apttus__Agreement_Clause__c.object-meta.xml
<CustomObject>
    <description>Represents a clause associated with an agreement</description>
    <label>Agreement Clause</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/txt_SAPExternalLineItemId__c.field-meta.xml
<CustomField>
    <fullName>txt_SAPExternalLineItemId__c</fullName>
    <externalId>true</externalId>
    <label>SAP External Line Item Id</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/GearsetExternalId__c.field-meta.xml
<CustomField>
    <fullName>GearsetExternalId__c</fullName>
    <description>Field created by Gearset wizard. It is necessary to migrate the data between environments. All CPQ objects that contain configurable data has this Gearset External ID</description>
    <externalId>true</externalId>
    <label>Gearset External ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/GearsetExternalId__c.field-meta.xml
<CustomField>
    <fullName>GearsetExternalId__c</fullName>
    <description>The field is required by Gearset for comparison and deployment of CPQ configuration.</description>
    <externalId>true</externalId>
    <label>Gearset External ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Approver associated with this Approval.</description>
    <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
    <label>Approver</label>
    <referenceTo>sbaa__Approver__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approver__c/sbaa__Approver__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Frameworks/TestFactory/TestFactory.cls
/**
* @author       APC
* @date         08/04/2025
* @description  TestFactory framework: TestFactory parent class
*/
@isTest
public with sharing class TestFactory {
	/**
	* @author       APC
	* @description  createSObject constructor
	* @param		sObj SObject
	* @return		SObject
	*/
	public static SObject createSObject(SObject sObj) {
		// Check what type of object we are creating and add any defaults that are needed.
		String objectName = String.valueOf(sObj.getSObjectType());
		// Construct the default values class. Salesforce doesn't allow '__' in class names
		String defaultClassName = objectName.replaceAll('__(c|C)$|__', '') + 'Defaults';
		// If there is a class that exists for the default values, then use them
		if (Type.forName('TestFactoryDefaults.' + defaultClassName) != null) {
			sObj = createSObject(sObj, 'TestFactoryDefaults.' + defaultClassName);
		}
		return sObj;
	}

	/**
	* @author       APC
	* @description  createSObject constructor with boolean to choose between insert the row or not
	* @param		sObj SObject
	* @param		doInsert Boolean
	* @return		SObject
	*/
	public static SObject createSObject(SObject sObj, Boolean doInsert) {
		SObject retObject = createSObject(sObj);
		if (doInsert) {
			insert retObject;
		}
		return retObject;
	}

	/**
	* @author       APC
	* @description  createSObject constructor with defaultClassName param
	* @param		sObj SObject
	* @param		defaultClassName String
	* @return		SObject
	*/
	public static SObject createSObject(SObject sObj, String defaultClassName) {
		// Create an instance of the defaults class so we can get the Map of field defaults
		Type typ = Type.forName(defaultClassName);
		if (typ == null) {
			Throw new TestFactoryException('Invalid defaults class.');
		}
		FieldDefaults defaults = (FieldDefaults)typ.newInstance();
		addFieldDefaults(sObj, defaults.getFieldDefaults());
		return sObj;
	}

	/**
	* @author       APC
	* @description  createSObject constructor
	* @param		sObj SObject
	* @param		defaultClassName String
	* @param		doInsert Boolean
	* @return		SObject
	*/
	public static SObject createSObject(SObject sObj, String defaultClassName, Boolean doInsert) {
		SObject retObject = createSObject(sObj, defaultClassName);
		if (doInsert) {
			insert retObject;
		}
		return retObject;
	}

	/**
	* @author       APC
	* @description  createSObject constructor
	* @param		sObj SObject
	* @param		numberOfObjects Integer
	* @return		SObject[]
	*/
	public static SObject[] createSObjectList(Sobject sObj, Integer numberOfObjects) {
		return createSObjectList(sObj, numberOfObjects, (String)null);
	}

	/**
	* @author       APC
	* @description  createSObject constructor
	* @param		sObj SObject
	* @param		numberOfObjects Integer
	* @param		doInsert Boolean
	* @return		SObject[]
	*/
	public static SObject[] createSObjectList(SObject sObj, Integer numberOfObjects, Boolean doInsert) {
		SObject[] retList = createSObjectList(sObj, numberOfObjects, (String)null);
		if (doInsert) {
			insert retList;
		}
		return retList;
	}

	/**
	* @author       APC
	* @description  createSObject constructor
	* @param		sObj SObject
	* @param		numberOfObjects Integer
	* @param		defaultClassName String
	* @param		doInsert Boolean
	* @return		SObject[]
	*/
	public static SObject[] createSObjectList(SObject sObj, Integer numberOfObjects, String defaultClassName, Boolean doInsert) {
		SObject[] retList = createSObjectList(sObj, numberOfObjects, defaultClassName);
		if (doInsert) {
			insert retList;
		}
		return retList;
	}

	/**
	* @author       APC
	* @description  createSObject constructor
	* @param		sObj SObject
	* @param		numberOfObjects Integer
	* @param		defaultClassName String
	* @return		SObject[]
	*/
	public static SObject[] createSObjectList(Sobject sObj, Integer numberOfObjects, String defaultClassName) {
		SObject[] sObjs = new SObject[] {};
		SObject newObj;

		// Get one copy of the object
		if (defaultClassName == null) {
			newObj = createSObject(sObj);
		} else {
			newObj = createSObject(sObj, defaultClassName);
		}

		// Get the name field for the object
		String nameField = String.valueOf(nameFieldMap.get(sObj.getSObjectType()));
	// namefield is 
        if (nameField == null) {
			nameField = 'Name';
		}
		Boolean nameIsAutoNumber = sObj.getSobjectType().getDescribe().fields.getMap().get(nameField).getDescribe().isAutoNumber();
         // Boolean nameIsAutoNumber = sObj.getSobjectType().getDescribe().fields.getMap().get(nameField).getDescribe().isAutoNumber() != null ? sObj.getSobjectType().getDescribe().fields.getMap().get(nameField).getDescribe().isAutoNumber() : false;
		// Clone the object the number of times requested. Increment the name field so each record is unique
		for (Integer i = 0; i < numberOfObjects; i++) {
			SObject clonedSObj = newObj.clone(false, true);
			if (!nameIsAutoNumber) {
				clonedSObj.put(nameField, (String)clonedSObj.get(nameField) + ' ' + i);
			}
			sObjs.add(clonedSObj);
		}
		return sObjs;
	}

	/**
	* @author       APC
	* @description  createSObject constructor
	* @param		sObj SObject
	* @param		defaults Map<Schema.SObjectField, Object>
	*/
	private static void addFieldDefaults(SObject sObj, Map<Schema.SObjectField, Object> defaults) {
		// Loop through the map of fields and if they weren't specifically assigned, fill them.
		Map<String, Object> populatedFields = sObj.getPopulatedFieldsAsMap();
		for (Schema.SObjectField field : defaults.keySet()) {
			if (!populatedFields.containsKey(String.valueOf(field))) {
				sObj.put(field, defaults.get(field));
			}
		}
	}

	/**
	* @author       APC
	* @description  When we create a list of SObjects, we need to have a unique field for the insert if there isn't an autonumber field.
					Usually we use the Name field, but some objects don't have a name field.
	*/
	private static Map<Schema.SObjectType, Schema.SObjectField> nameFieldMap = new Map<Schema.SObjectType, Schema.SObjectField> {
		Account.sObjectType => Account.txt_AthenaUUID__c,
		Contact.sObjectType => Contact.LastName,
		Opportunity.sObjectType => Opportunity.Name,
		Order.sObjectType => Order.Name,
		Product2.sObjectType => Product2.Name,
		Quote.sObjectType => Quote.Name,
		Apttus__Agreement_Clause__c.sObjectType => Apttus__Agreement_Clause__c.Apttus__ContentId__c,
        sbaa__Approval__c.SObjectType => sbaa__Approval__c.Name,
        sbaa__Approver__c.SObjectType => sbaa__Approver__c.Name,
        ContentVersion.SObjectType => ContentVersion.Title,
        ContentDocumentLink.SObjectType => ContentDocumentLink.ContentDocumentId,
		OrderItem.sObjectType => OrderItem.txt_SAPExternalLineItemId__c,
		PricebookEntry.sObjectType => PricebookEntry.GearsetExternalId__c,
		SBQQ__QuoteLine__c.sObjectType => SBQQ__QuoteLine__c.Name
	};
     

	public class TestFactoryException extends Exception {}

	/**
	* @author       APC
	* @description  Use the FieldDefaults interface to set up values you want to default in for all objects.
	*/
	public interface FieldDefaults {
		Map<Schema.SObjectField, Object> getFieldDefaults();
	}

}