force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/cur_Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>cur_Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/cur_Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>cur_Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Callouts/CreditLimitCallouts.cls
/**
* @author       APB
* @description  CreditLimitCallouts: Class used to do the vertex and credit limit callouts
*/
public with sharing class CreditLimitCallouts {

    public static final String REMAININGURL = '/sap-tax-service/tax/v1/quote';

    /**
	* @author       APB
	* @description  getVertexInformation method
	* @param		quoteToCalculate SBQQ__Quote__c
    * @param		orderToCalculate Order
	* @return		HttpResponse
	*/
    public static HttpResponse getVertexInformation(SBQQ__Quote__c quoteToCalculate,Order orderToCalculate){

        Http vertexHttp= new Http();
        HttpRequest vertexRequest = new HttpRequest();
        HttpResponse vertexResponse = new HttpResponse();

        DateTime todayDateTime = DateTime.now();

        vertexRequest.setEndpoint('callout:vertex_usernamePass'+ REMAININGURL);
        vertexRequest.setHeader('Content-Type','application/json');

        vertexRequest.setMethod('POST');

        String finalVertexBody;

        if(quoteToCalculate != null && quoteToCalculate.SBQQ__Status__c == 'Accepted'){

            String bodyWrapper = JSON.serialize(VertexIntManager.createRequest(todayDateTime,quoteToCalculate.SBQQ__Account__r.BillingCountry));
            finalVertexBody = CreditLimitUtilMethods.formatRequest(bodyWrapper);

        }else if(orderToCalculate != null && orderToCalculate.Status == 'Activated'){
        	String bodyWrapper = JSON.serialize(VertexIntManager.createRequest(todayDateTime,orderToCalculate.Account.BillingCountry));
            finalVertexBody = CreditLimitUtilMethods.formatRequest(bodyWrapper);
        }
        vertexRequest.setBody(finalVertexBody);
        vertexResponse = vertexHttp.send(vertexRequest);

        return vertexResponse;

    }

    /**
	* @author       APB
	* @description  startCreditLimitCallouts method
	* @param		quoteToCalculate SBQQ__Quote__c
    * @param		orderToCalculate Order
    * @param		actualAccount Account
	* @return		HttpResponse
	*/
    public static HttpResponse startCreditLimitCallouts(SBQQ__Quote__c quoteToCalculate,Order orderToCalculate,Account actualAccount){

        String orgId = [SELECT Id FROM Organization WITH USER_MODE LIMIT 1].Id;
        HttpResponse creditLimitResponse = new HttpResponse();
        HttpRequest request = new HttpRequest();
        Http creditLimitHttp= new Http();

        request.setHeader('Content-Type','application/json');
        request.setHeader('accept','application/json');

        request.setMethod('POST');
        String finalCreditLimitBody;

        if(quoteToCalculate != null && quoteToCalculate.SBQQ__Status__c == 'Accepted'){

        	request.setEndpoint('callout:creditLimitCheckOuathCallout');

            String bodyWrapper = JSON.serialize(CreditLimitWrapperManager.createCreditWorthinessRequest(quoteToCalculate.cur_Current_Credit_Limit_including_VAT__c,quoteToCalculate.CurrencyIsoCode,quoteToCalculate.SBQQ__Account__r.txt_AthenaUUID__c ));
            finalCreditLimitBody= CreditLimitUtilMethods.formatRequest(bodyWrapper);

        }else if(orderToCalculate != null && orderToCalculate.Status == 'Activated'){

         	request.setEndpoint('callout:creditLimitCheckOuathCallout');
            String bodyWrapper = JSON.serialize(CreditLimitWrapperManager.createCreditWorthinessRequest(orderToCalculate.cur_Current_Credit_Limit_including_VAT__c,orderToCalculate.CurrencyIsoCode,orderToCalculate.Account.txt_AthenaUUID__c));
            finalCreditLimitBody= CreditLimitUtilMethods.formatRequest(bodyWrapper);

        }else if(actualAccount != null){

         	request.setEndpoint('callout:CreditLimitOuathAccount');
            String bodyWrapper = JSON.serialize(CreditLimitWrapperManager.createAccountRequest(orgId,actualAccount.BillingCountry,actualAccount.txt_AthenaUUID__c));
            finalCreditLimitBody= CreditLimitUtilMethods.formatRequest(bodyWrapper);

        }

        request.setBody(finalCreditLimitBody);

        if(request.getBody() != null && request.getBody() != ''){
            creditLimitResponse = creditLimitHttp.send(request);
        }

        return creditLimitResponse;

    }
}