force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Bill_To_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Country__c</fullName>
    <description>Contains Bill To Country information related to its respective Bill-to Account</description>
    <formula>lkp_BillToAccount__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bill_To_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Country__c</fullName>
    <description>Contains Bill To Country information related to its respective Bill-to Account</description>
    <formula>lkp_BillToAccount__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreditLimitWrapperManagerTest.cls
@isTest
public class CreditLimitWrapperManagerTest {

    @testSetup
    static void initObjects(){
        Account[] testAccountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        testAccountList[0].CurrencyIsoCode = 'EUR';
        testAccountList[0].txt_AthenaUUID__c='123213123';
        insert testAccountList;
        
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c [])TestFactory.createSObjectList(new SBQQ__Quote__c(),1);
        quoteList[0].SBQQ__Status__c = 'Draft';
        quoteList[0].CurrencyIsoCode = 'EUR';
        quoteList[0].SBQQ__Account__r = testAccountList[0];
        insert quoteList;
        
        Order[] orderList = (Order [])TestFactory.createSObjectList(new Order(),1);
        orderList[0].AccountId= testAccountList[0].Id;
        insert orderList;
    }
    
    @isTest
	static void createAccountCreditLimitRequest() {
    
    	Account testAccount = [SELECT Id,BillingCountry,CurrencyIsoCode from Account LIMIT 1];
        
    	Test.startTest();
    	
        CreditLimitWrapperManager.createAccountRequest('321323', testAccount.CurrencyIsoCode, testAccount.Id);
        Test.stopTest();
	}
    
    @isTest
	static void createQuoteCreditLimitRequest() {
    
    	SBQQ__Quote__c quoteTest = [SELECT Id,SBQQ__Status__c,Bill_To_Country__c,Current_Credit_Limit_including_VAT__c,CurrencyIsoCode,SBQQ__Account__r.txt_AthenaUUID__c,SBQQ__Account__c from SBQQ__Quote__c LIMIT 1];
        quoteTest.Current_Credit_Limit_including_VAT__c=10;
        quoteTest.SBQQ__Status__c='Accepted';
        update quoteTest;
        
    	Test.startTest();
    	
        CreditLimitWrapperManager.createCreditWorthinessRequest('21321312', quoteTest.Current_Credit_Limit_including_VAT__c, quoteTest.CurrencyIsoCode, quoteTest.SBQQ__Account__c);
        Test.stopTest();
	}
    
    @isTest
	static void createOrderCreditLimitRequest() {
    
    	Order orderTest = [SELECT Id,Current_Credit_Limit_including_VAT__c,CurrencyIsoCode,Account.txt_AthenaUUID__c,AccountId from Order LIMIT 1];
        
    	Test.startTest();
    	
        CreditLimitWrapperManager.createCreditWorthinessRequest('21321312', orderTest.Current_Credit_Limit_including_VAT__c, orderTest.CurrencyIsoCode, orderTest.AccountId);
        Test.stopTest();
	}
}