force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Bill_To_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Country__c</fullName>
    <description>Contains Bill To Country information related to its respective Bill-to Account</description>
    <formula>lkp_BillToAccount__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bill_To_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Country__c</fullName>
    <description>Contains Bill To Country information related to its respective Bill-to Account</description>
    <formula>lkp_BillToAccount__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreditGetAuthorizationsTest.cls
@isTest
public class CreditGetAuthorizationsTest {
	
     @testSetup
    static void initObjects(){
        Account[] testAccountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        testAccountList[0].CurrencyIsoCode = 'EUR';
        testAccountList[0].txt_AthenaUUID__c='123213123';
        insert testAccountList;
        
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c [])TestFactory.createSObjectList(new SBQQ__Quote__c(),1);
        quoteList[0].SBQQ__Status__c = 'Draft';
        quoteList[0].CurrencyIsoCode = 'EUR';
        quoteList[0].SBQQ__Account__r = testAccountList[0];
        insert quoteList;
        
        Order[] orderList = (Order [])TestFactory.createSObjectList(new Order(),1);
        orderList[0].AccountId= testAccountList[0].Id;
        insert orderList;
    }
	
    
    @isTest
	static void testAuthCallouts() {
    	// Set mock callout class
    	
        Account testAccount = [SELECT Id from Account LIMIT 1];
        SBQQ__Quote__c quoteTest = [SELECT Id,SBQQ__Status__c,Bill_To_Country__c from SBQQ__Quote__c LIMIT 1];
        quoteTest.SBQQ__Status__c='Accepted';
        update quoteTest;
        
        Test.startTest();
    	Test.setMock(HttpCalloutMock.class, new VertexMockClass());
    	// This causes a fake response to be sent
    	// from the class that implements HttpCalloutMock.
    	HttpResponse response = CreditLimitCallouts.startVertexCallouts(false, true, false, quoteTest.Id, quoteTest, null);
    	// Verify that the response received contains fake values
    	String contentType = response.getHeader('Content-Type');
    	Assert.isTrue(contentType == 'application/json');
    	String actualValue = response.getBody();
    	System.debug(response.getBody());
    	CreditLimitGetAuthorizations.getAuthorizationToken(testAccount.Id);
        Test.stopTest();
	}
}