force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/pkl_MaterialType__c.field-meta.xml
<CustomField>
    <fullName>pkl_MaterialType__c</fullName>
    <description>Material type</description>
    <label>Material Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VERP</fullName>
            </value>
            <value>
                <fullName>SUBS</fullName>
            </value>
            <value>
                <fullName>SUBP</fullName>
            </value>
            <value>
                <fullName>YSER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/cur_CreditLimit__c.field-meta.xml
<CustomField>
    <fullName>cur_CreditLimit__c</fullName>
    <label>Current Account Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/cur_Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>cur_Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/lkp_BillToAccount__c.field-meta.xml
<CustomField>
    <fullName>lkp_BillToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Bill-to Account)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/lkp_ToolCoordinator__c.field-meta.xml
<CustomField>
    <fullName>lkp_ToolCoordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field that is needed for the Order interface. The contact of the customer that is responsible for the licences etc.</description>
    <label>Tool Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Tool Coordinator)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreditLimitApprovalController_Test.cls
@isTest
public class CreditLimitApprovalController_Test {

    @TestSetup
    static void setupTestData() {
        Account testAccountList = (Account)TestFactory.createSObject(new Account(),'TestFactoryDefaults.AccountDefaults', false);
        testAccountList.txt_AthenaUUID__c='4001000001';
        testAccountList.BillingCountry='DE';
        insert testAccountList;
        
        Contact[] testContactList = (Contact[])TestFactory.createSObjectList(new Contact(), 1);
        testContactList[0].AccountId = testAccountList.Id;
        insert testContactList;
        
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c [])TestFactory.createSObjectList(new SBQQ__Quote__c(),1);
        quoteList[0].SBQQ__Status__c = 'Draft';
        quoteList[0].SBQQ__Account__c = testAccountList.Id;
        //quoteList[0].lkp_BillToAccount__c= testAccountList[0].Id;
        insert quoteList;
        
        Product2[] productList = (Product2 [])TestFactory.createSObjectList(new Product2(),1);
        insert productList;
        
        SBQQ__QuoteLine__c[] quoteLineList = (SBQQ__QuoteLine__c [])TestFactory.createSObjectList(new SBQQ__QuoteLine__c(),1);
        quoteLineList[0].SBQQ__Quote__c= quoteList[0].Id;
        quoteLineList[0].SBQQ__Product__c= productList[0].Id;
        
        insert quoteLineList;
    }
    
    @isTest
    static void quoteDontHaveToolCoordinator(){
        Test.startTest();
        SBQQ__Quote__c quote= [Select id,lkp_ToolCoordinator__c from SBQQ__Quote__c LIMIT 1];
        System.assertEquals(null, quote.lkp_ToolCoordinator__c);
        Boolean hasSubProducts= CreditLimitApprovalController.hasSubsProducts(quote.Id);
        System.assertEquals(false,hasSubProducts);
        Test.stopTest();
    }
    
    @isTest
    static void quoteHaveToolCoordinatorButTheProductHasNotTheType(){
        Test.startTest();
        SBQQ__Quote__c quote= [Select id,lkp_ToolCoordinator__c from SBQQ__Quote__c LIMIT 1];
        Contact cont = [SELECT id from Contact LIMIT 1];
        quote.lkp_ToolCoordinator__c= cont.Id;
        update quote;
        System.assertNotEquals(null, quote.lkp_ToolCoordinator__c);
        Boolean hasSubProducts= CreditLimitApprovalController.hasSubsProducts(quote.Id);
        System.assertEquals(false,hasSubProducts);
        Test.stopTest();
    }
    
    @isTest
    static void quoteHaveToolCoordinatorAndTheProductHasTheType(){
        Test.startTest();
        SBQQ__Quote__c quote= [Select id,lkp_ToolCoordinator__c from SBQQ__Quote__c LIMIT 1];
        Contact cont = [SELECT id from Contact LIMIT 1];
        Product2 product= [select id from Product2 LIMIT 1];
        product.pkl_MaterialType__c= 'SUBS';
        update product;
       
        Boolean hasSubProducts= CreditLimitApprovalController.hasSubsProducts(quote.Id);
        System.assertEquals(true,hasSubProducts);
        Test.stopTest();
    }
    
    @isTest
    static void creditLimitGetQuote(){
        Test.startTest();
        
        SBQQ__Quote__c quoteToSend= [Select id from SBQQ__Quote__c LIMIT 1];
        StaticResource sr = [SELECT Body FROM StaticResource WHERE Name = 'vertexSuccess'];
		String vertexBody = sr.Body.toString();
        HttpCalloutMock res1 = new HTTPMockGenerator(200, vertexBody);
            
        StaticResource sr2 = [SELECT Body FROM StaticResource WHERE Name = 'creditLimitQuoteOrderExceded'];
		String creditLimitBody = sr2.Body.toString();
        HttpCalloutMock res2 = new HTTPMockGenerator(200, creditLimitBody);
        String remainingUrlVertex = '/sap-tax-service/tax/v1/quote';
        HttpMultiRequestMockGenerator multiMock = new HttpMultiRequestMockGenerator();
        multiMock.putMock('https://api.status.salesforce.com/v1/instances/DEU114S/status',new HTTPMockGenerator(200, '{"status":"OK"}'));
		multiMock.putMock('callout:vertex_usernamePass'+ remainingUrlVertex,res1);
		multiMock.putMock('callout:creditLimitCheckOuathCallout',res2);
        
        Test.setMock(HttpCalloutMock.class, multiMock);
        SBQQ__Quote__c quote= CreditLimitApprovalController.callCreditLimit(quoteToSend.Id);
        
        System.assertNotEquals(null, quote.cur_CreditLimit__c);
        
        System.assertNotEquals(null, quote.cur_Current_Credit_Limit_including_VAT__c);
         
        Test.stopTest();
    }
}