force-app/main/default/objects/Account/fields/txt_AthenaUUID__c.field-meta.xml
<CustomField>
    <fullName>txt_AthenaUUID__c</fullName>
    <description>Defines the Athena unique identifier for Account;
Unique field</description>
    <inlineHelpText>Defines the Athena unique identifier for Account;
Unique field</inlineHelpText>
    <label>Bosch Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bill_To_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Country__c</fullName>
    <description>Contains Bill To Country information related to its respective Bill-to Account</description>
    <formula>lkp_BillToAccount__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Current_Credit_Limit_including_VAT__c.field-meta.xml
<CustomField>
    <fullName>Current_Credit_Limit_including_VAT__c</fullName>
    <label>Current Credit Limit including VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteSelector.cls
public with sharing class QuoteSelector extends fflib_SObjectSelector {
     public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
           SBQQ__Quote__c.SBQQ__Status__c,
           SBQQ__Quote__c.Current_Credit_Limit_including_VAT__c, 
           SBQQ__Quote__c.Bill_To_Country__c,
           SBQQ__Quote__c.SBQQ__NetAmount__c,
           SBQQ__Quote__c.CurrencyIsoCode
            
        };
    
    }

    public List<SBQQ__Quote__c> selectQuoteInfo(Set<Id> idSet) {
    List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
    for(SBQQ__Quote__c quote : Database.query(
            newQueryFactory(false)
                .selectField(SBQQ__Quote__c.SBQQ__Status__c)
                .selectField(SBQQ__Quote__c.SBQQ__Account__c)
                .selectField(SBQQ__Quote__c.Current_Credit_Limit_including_VAT__c)
                .selectField(SBQQ__Quote__c.Bill_To_Country__c)
                .selectField(SBQQ__Quote__c.SBQQ__NetAmount__c)
                .selectField(SBQQ__Quote__c.CurrencyIsoCode)
                .selectField('SBQQ__Account__r.BillingCountry')
                .selectField('SBQQ__Account__r.txt_AthenaUUID__c')
                .setCondition('id in :idSet')
                .toSOQL()))
    {
        quotes.add(quote);
    }
        return quotes;
    }

    public Schema.SObjectType getSObjectType() {
        return SBQQ__Quote__c.sObjectType;
    }
    public List<SBQQ__Quote__c> selectById(Set<ID> idSet) {
        return (List<SBQQ__Quote__c>) selectSObjectsById(idSet);
    }
   
}