force-app/main/default/objects/cs_BlockFieldExemption__c/cs_BlockFieldExemption__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Block Field Exemption</label>
</CustomObject>

force-app/main/default/objects/cs_BlockFieldExemption__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cs_BlockFieldExemption__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>ObjectName</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>This is the Sold-To Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ExpirationDate__c</fullName>
    <defaultValue>IF(NOT(ISBLANK($Setup.SBQQ__GeneralSettings__c.SBQQ__DefaultQuoteValidity__c)),TODAY() + $Setup.SBQQ__GeneralSettings__c.SBQQ__DefaultQuoteValidity__c, null)</defaultValue>
    <description>Date after which the Quote is no longer valid</description>
    <inlineHelpText>Date after which the Quote is no longer valid</inlineHelpText>
    <label>Expires On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteLockTriggerTest.cls
/**
 * @description Test class for QuoteLockTrigger and QuoteLock domain class
 * @author TLQ1KOR
 * @date 2025
 */
@IsTest
private class QuoteLockTriggerTest {
    
    @TestSetup
    static void setup() {
        // Create custom setting exemptions
        insert new cs_BlockFieldExemption__c(
            Name = 'Primary', 
            ObjectName__c = 'SBQQ__Quote__c', 
            FieldName__c = 'SBQQ__Primary__c'
        );
    }
    
    @IsTest
    static void testTriggerExecutionDraftQuote() {
        // Create test data with Draft status
        Account[] accountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        insert accountList;
        
        Opportunity[] oppList = (Opportunity[])TestFactory.createSObjectList(new Opportunity(), 1, 'TestFactoryDefaults.OpportunityDefault');
        oppList[0].AccountId = accountList[0].Id;
        insert oppList;
        
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c[])TestFactory.createSObjectList(new SBQQ__Quote__c(), 1);
        quoteList[0].SBQQ__Status__c = 'Draft';
        quoteList[0].SBQQ__Account__c = accountList[0].Id;
        quoteList[0].SBQQ__Opportunity2__c = oppList[0].Id;
        insert quoteList;
        Test.startTest();
        quoteList[0].SBQQ__Primary__c = true;
        Database.SaveResult result = Database.update(quoteList[0], false);
        Test.stopTest();
        
        // Then - Draft quote should be updateable
        System.assert(result.isSuccess(), 'Draft quote should be updateable');
    }
    
    @IsTest
    static void testQuoteLockingFunctionality() {
        Account[] accountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        insert accountList;
        
        Opportunity[] oppList = (Opportunity[])TestFactory.createSObjectList(new Opportunity(), 1, 'TestFactoryDefaults.OpportunityDefault');
        oppList[0].AccountId = accountList[0].Id;
        insert oppList;
        
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c[])TestFactory.createSObjectList(new SBQQ__Quote__c(), 1);
        quoteList[0].SBQQ__Status__c = 'Draft';  
        quoteList[0].SBQQ__Account__c = accountList[0].Id;
        quoteList[0].SBQQ__Opportunity2__c = oppList[0].Id;
        insert quoteList;

        Test.startTest();
        quoteList[0].SBQQ__Primary__c = !quoteList[0].SBQQ__Primary__c; 
        Database.SaveResult result = Database.update(quoteList[0], false);
        Test.stopTest();
        System.assert(result.isSuccess(), 'Exempt field modification should be allowed on locked quote');
    }
    
    @IsTest
    static void testQuoteLockingBlocked() {
        Account[] accountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        insert accountList;
        
        Opportunity[] oppList = (Opportunity[])TestFactory.createSObjectList(new Opportunity(), 1, 'TestFactoryDefaults.OpportunityDefault');
        oppList[0].AccountId = accountList[0].Id;
        insert oppList;
        
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c[])TestFactory.createSObjectList(new SBQQ__Quote__c(), 1);
        quoteList[0].SBQQ__Status__c = 'Draft';
        quoteList[0].SBQQ__Account__c = accountList[0].Id;
        quoteList[0].SBQQ__Opportunity2__c = oppList[0].Id;
        insert quoteList;

        Test.startTest();
        Database.SaveResult result = Database.update(quoteList[0], false);
        Test.stopTest();
 
        System.assert(result.isSuccess(), 'No-change update should succeed');
    }
    
    @IsTest
    static void testDomainClass() {
        Account[] accountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        insert accountList;
        
        Opportunity[] oppList = (Opportunity[])TestFactory.createSObjectList(new Opportunity(), 1, 'TestFactoryDefaults.OpportunityDefault');
        oppList[0].AccountId = accountList[0].Id;
        insert oppList;
        
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c[])TestFactory.createSObjectList(new SBQQ__Quote__c(), 1);
        quoteList[0].SBQQ__Status__c = 'Draft';
        quoteList[0].SBQQ__Account__c = accountList[0].Id;
        quoteList[0].SBQQ__Opportunity2__c = oppList[0].Id;
        insert quoteList;

        Test.startTest();
       List<SBQQ__Quote__c> quoteListForDomain = new List<SBQQ__Quote__c>(quoteList);
       QuoteLock domain = new QuoteLock(quoteListForDomain); 
        List<SBQQ__Quote__c> quotes = domain.getQuotes();
        Test.stopTest();
        

        System.assertEquals(1, quotes.size(), 'Domain class should return quotes');
        System.assertEquals('Draft', quotes[0].SBQQ__Status__c, 'Quote status should be preserved');
            }
       @IsTest
    static void testValidationLogic() {
        Account[] accountList = (Account[])TestFactory.createSObjectList(new Account(), 1);
        insert accountList;
        
        Opportunity[] oppList = (Opportunity[])TestFactory.createSObjectList(new Opportunity(), 1, 'TestFactoryDefaults.OpportunityDefault');
        oppList[0].AccountId = accountList[0].Id;
        insert oppList;
        
        SBQQ__Quote__c[] quoteList = (SBQQ__Quote__c[])TestFactory.createSObjectList(new SBQQ__Quote__c(), 1);
        quoteList[0].SBQQ__Status__c = 'Draft';
        quoteList[0].SBQQ__Account__c = accountList[0].Id;
        quoteList[0].SBQQ__Opportunity2__c = oppList[0].Id;
        insert quoteList;

        SBQQ__Quote__c oldQuote = quoteList[0].clone(true, true, true, true);
        SBQQ__Quote__c newQuote = quoteList[0].clone(true, true, true, true);

        newQuote.SBQQ__Status__c = 'Accepted';
        if (newQuote.getSObjectType().getDescribe().fields.getMap().containsKey('SBQQ__ExpirationDate__c')) {
            newQuote.put('SBQQ__ExpirationDate__c', Date.today().addDays(30));
        }
        
        Map<Id, SObject> oldRecordsMap = new Map<Id, SObject>();
        oldRecordsMap.put(oldQuote.Id, oldQuote);

        Test.startTest();
        List<SBQQ__Quote__c> quotesForDomain = new List<SBQQ__Quote__c>{newQuote};
        QuoteLock domain = new QuoteLock(quotesForDomain);
        
        try {
            domain.onBeforeUpdate(oldRecordsMap);
        } catch (Exception e) {
            
        }
        Test.stopTest();

        System.assertEquals(1, domain.getQuotes().size(), 'Domain should contain the quote');
    }
}