force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/lkp_ToolCoordinator__c.field-meta.xml
<CustomField>
    <fullName>lkp_ToolCoordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field that is needed for the Order interface. The contact of the customer that is responsible for the licences etc.</description>
    <label>Tool Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Tool Coordinator)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreditLimitApprovalController.cls
public class CreditLimitApprovalController {

    @AuraEnabled
	public static Boolean hasSubsProducts(Id quoteId) {
    
        Set<Id> quoteIds= new Set<Id>();
        quoteIds.add(quoteId);
        
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
    	quote = new QuoteSelector().selectQuoteToolCoordinator(quoteIds)[0];
        
        Set<String> swTypes = new Set<String>{ 'SUBS', 'SUBP' };
        if (quote.lkp_ToolCoordinator__c != null){
      		return false;
    	}
        
        List<SBQQ__QuoteLine__c>  quoteLineItems = new QuoteLineItemSelector().selectQuoteLineItems(quoteIds);
    	for (SBQQ__QuoteLine__c ql : quoteLineItems) {
        	if (ql.SBQQ__Product__r != null &&
            	swTypes.contains(ql.SBQQ__Product__r.pkl_MaterialType__c)) {
            	return true;
        	}
    	}

    	return false;
	}

	@AuraEnabled
	public static SBQQ__Quote__c callCreditLimit(Id quoteId) {

		Set<Id> quoteIds = new Set<Id>();
        quoteIds.add(quoteId);
		SBQQ__Quote__c quote = new SBQQ__Quote__c();
    
        CreditLimitManager.callGetLimit('SBQQ__Quote__c', quoteId);
		quote = new QuoteSelector().selectQuoteInfo(quoteIds)[0];

		return quote;
	}

}