Salesforce CPQ/main/default/objects/Order/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce CPQ/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/flink_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>flink_Opportunity__c</fullName>
    <description>Opportunity related to the quote submitted for approval.</description>
    <formula>HYPERLINK(&quot;/lightning/r/Opportunity/&quot; &amp; Quote__r.SBQQ__Opportunity2__r.Id &amp; &quot;/view&quot;, Quote__r.SBQQ__Opportunity2__r.Name, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Number of quote for which the approval request is generated.</description>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__ApprovedBy__c.field-meta.xml
<CustomField>
    <fullName>sbaa__ApprovedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who approved this Approval</description>
    <inlineHelpText>User who approved this Approval</inlineHelpText>
    <label>Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApprovedApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Approver associated with this Approval.</description>
    <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
    <label>Approver</label>
    <referenceTo>sbaa__Approver__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__RejectedBy__c.field-meta.xml
<CustomField>
    <fullName>sbaa__RejectedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who rejected this Approval</description>
    <inlineHelpText>User who rejected this Approval</inlineHelpText>
    <label>Rejected By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RejectedApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Status__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Status__c</fullName>
    <description>Status of this approval.</description>
    <inlineHelpText>Status of this approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sbaa__Approver__c/sbaa__Approver__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approver__c/fields/sbaa__User__c.field-meta.xml
<CustomField>
    <fullName>sbaa__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If Approver is a single User, lookup to that User</description>
    <inlineHelpText>If Approver is a single User, lookup to that User</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce CPQ/main/default/objects/SubscribedQuoteLine__c/SubscribedQuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce CPQ/main/default/objects/SubscribedQuoteLine__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApprovalController.cls
/**
* @File Name : ApprovalController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : October 30, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | October 30, 2025 |   | Initial Version
**/

public with sharing class ApprovalController {
    @AuraEnabled(cacheable=true)
    public static List<sbaa__Approval__c> getMyApprovals() {
        List<String> excludedStatuses = new List<String>{'Rejected', 'Approved'};
        Id userId = UserInfo.getUserId();
		Set<Id> userGroupIds = new Set<Id>();
    	for (GroupMember gm : [
        	SELECT GroupId 
        	FROM GroupMember 
        	WHERE UserOrGroupId = :userId
    	]) {
        	userGroupIds.add(gm.GroupId);
    	}

	    Set<Id> approverIds = new Set<Id>();
	    for (sbaa__Approver__c approver : [
    	    SELECT Id 
	        FROM sbaa__Approver__c 
	        WHERE sbaa__User__c = :userId 
			OR sbaa__GroupId__c IN :userGroupIds
    	]) {
        	approverIds.add(approver.Id);
    	}       
    	return [
        	SELECT Id, Name, sbaa__Status__c, Quote__c, Quote__r.Name, CreatedDate
        	FROM sbaa__Approval__c
        	WHERE sbaa__Approver__c IN :approverIds
        	AND sbaa__Status__c NOT IN :excludedStatuses
        	ORDER BY CreatedDate DESC
    	];
    }

	@AuraEnabled(cacheable=true)
    public static List<sbaa__Approval__c> getMyHistoryApprovals() {
        Id userId = UserInfo.getUserId();
        return [
            SELECT Id, Name, sbaa__Status__c, LastModifiedDate,
                   sbaa__ApprovedBy__r.Name,
                   sbaa__RejectedBy__r.Name,
                   Quote__r.Name,
                   flink_Opportunity__c
            FROM sbaa__Approval__c
            WHERE sbaa__ApprovedBy__c = :userId
               OR sbaa__RejectedBy__c = :userId
            ORDER BY LastModifiedDate DESC
        ];
    }
}