force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Approver associated with this Approval.</description>
    <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
    <label>Approver</label>
    <referenceTo>sbaa__Approver__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approver__c/sbaa__Approver__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approver__c/fields/sbaa__User__c.field-meta.xml
<CustomField>
    <fullName>sbaa__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If Approver is a single User, lookup to that User</description>
    <inlineHelpText>If Approver is a single User, lookup to that User</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Selectors/ApprovalSelector.cls
/**
* @author       APB
* @description  ApprovalSelector: Selector class for approvals
*/
public with sharing class ApprovalSelector extends fflib_SObjectSelector {

    /**
	* @author       APB
	* @description  approval getSObjectFieldList method
	* @return		List<Schema.SObjectField>
	*/
     public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
           
        };
    }

    /**
	* @author       APB
	* @description  approval getApprovalApprovers method
    * @param		idSet Set<ID>
	* @return		List<sbaa__Approval__c>
	*/
    public List<sbaa__Approval__c> getApprovalApprovers(Set<Id> idSet) {
    List<sbaa__Approval__c> approvals = new List<sbaa__Approval__c>();
    for(sbaa__Approval__c approval : Database.query(
            newQueryFactory(false)
                .selectField('sbaa__Approver__r.sbaa__User__c')
                .selectField('sbaa__Approver__r.sbaa__GroupId__c')
                .setCondition('id in :idSet')
                .toSOQL()))
    {
        approvals.add(approval);
    }
        return approvals;
    }

    /**
	* @author       APB
	* @description  approval getSObjectType method
	* @return		Schema.SObjectType
	*/
    public Schema.SObjectType getSObjectType() {
        return sbaa__Approval__c.sObjectType;
    }

    /**
	* @author       APB
	* @description  approval selectById method
    * @param		idSet Set<ID>
	* @return		List<sbaa__Approval__c>
	*/
    public List<sbaa__Approval__c> selectById(Set<ID> idSet) {
        return (List<sbaa__Approval__c>) selectSObjectsById(idSet);
    }
}