force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__ApprovedBy__c.field-meta.xml
<CustomField>
    <fullName>sbaa__ApprovedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who approved this Approval</description>
    <inlineHelpText>User who approved this Approval</inlineHelpText>
    <label>Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApprovedApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Approver associated with this Approval.</description>
    <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
    <label>Approver</label>
    <referenceTo>sbaa__Approver__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approver__c/sbaa__Approver__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approver__c/fields/sbaa__User__c.field-meta.xml
<CustomField>
    <fullName>sbaa__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If Approver is a single User, lookup to that User</description>
    <inlineHelpText>If Approver is a single User, lookup to that User</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetApproversEmail.cls
public without sharing class GetApproversEmail {


    @InvocableMethod(label='Send email to approvers' description='Method used to get the ids of the approvers to send the notification')
    public static List<OutputParameters> getApproverIds(List<InputVariables> listApprovals) {
 
        Set<Id> approvalIds = new Set<Id>(listApprovals[0].approvalIds);

        List<sbaa__Approval__c> approvals = new ApprovalSelector().getApprovalApprovers(approvalIds);

        List<String> approverIds= new List<String>(); 
       
        for (sbaa__Approval__c approval : approvals) {
            if (approval.sbaa__Approver__r.sbaa__User__c != null) {
                approverIds.add(approval.sbaa__Approver__r.sbaa__User__c);
            } else if (approval.sbaa__Approver__r.sbaa__GroupId__c != null) {
                approverIds.add(approval.sbaa__ApprovedBy__c);
            }
        }

        List<OutputParameters> outputParameters = new List<OutputParameters>();
    
        OutputParameters outputParameter = new OutputParameters();
        outputParameter.approverIds= approverIds;

        outputParameters.add(outputParameter);
        return outputParameters;

    }

    public class InputVariables {
        @InvocableVariable(label='Approvals' description='List of approvals')
        public List<Id> approvalIds;
    }
    public class OutputParameters {
        @InvocableVariable(label='Approver Ids' description='List of approver Ids')
        public List<String> approverIds;
    }
}